### ISSUE TITLE
can't launch pgcli: assertion error

### ISSUE THREAD

**Issue by gantsevdenis** [dbcli/pgcli#1055]
## Description
```denis ~ $ pgcli -h localhost -U postgres -d postgres
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.20.1', 'console_scripts', 'console')()
  File "/home/denis/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/denis/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/denis/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/denis/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/pgcli/pgcli/main.py", line 595, in cli
    pgcli.run_cli()
  File "/usr/share/pgcli/pgcli/main.py", line 278, in run_cli
    self.cli = self._build_cli()
  File "/usr/share/pgcli/pgcli/main.py", line 408, in _build_cli
    cli = CommandLineInterface(application=application)
  File "/home/denis/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 69, in __init__
    assert isinstance(eventloop, EventLoop), 'Passing an eventloop is required.'
AssertionError: Passing an eventloop is required.
denis ~ $ pgcli --version
Version: 0.20.1
denis ~ $ python --version
Python 3.6.3 :: Anaconda, Inc.
denis ~ $ uname -a
Linux denis-OMEN-by-HP-Laptop 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by j-bennet** [comment]
The latest version of pgcli is 2.1.0. Please try updating it from pip:

`pip install -U pgcli`

**Comment by dbaty** [comment]
No response for 4 years. I am closing this issue.
