### ISSUE TITLE
cannot import name 'CommandLineInterface'

### ISSUE THREAD

**Issue by karambaq** [dbcli/pgcli#1075]
## Description
```
$ pgcli                                                                                                    
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 11, in <module>
    load_entry_point('pgcli==1.6.0', 'console_scripts', 'console')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/share/pgcli/pgcli/main.py", line 24, in <module>
    from prompt_toolkit import CommandLineInterface, Application, AbortAction
ImportError: cannot import name 'CommandLineInterface'
```

## Your environment

- [ ] Ubuntu 18.04

```
$ pip3 freeze                                                                                              
aiohttp==3.5.4
appdirs==1.4.3
asn1crypto==0.24.0
async-timeout==3.0.1
attrs==17.4.0
Automat==0.6.0
backcall==0.1.0
beautifulsoup4==4.7.1
blinker==1.4
bs4==0.0.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
click==6.7
cloud-init==19.1
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.7
cssselect==1.0.3
dataclasses==0.6
dateparser==0.7.1
decorator==4.4.0
distro-info===0.18ubuntu0.18.04.1
fake-useragent==0.1.11
future==0.17.1
greenlet==0.4.12
httplib2==0.9.2
humanize==0.5.1
hyperlink==17.3.1
idna==2.6
idna-ssl==1.1.0
incremental==16.10.1
ipython==7.5.0
ipython-genutils==0.2.0
jedi==0.14.0
Jinja2==2.10
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
lxml==4.3.4
MarkupSafe==1.0
maya==0.6.1
msgpack==0.5.6
multidict==4.5.2
neovim==0.2.0
netifaces==0.10.4
oauthlib==2.0.6
PAM==0.4.2
parse==1.12.0
parso==0.5.0
pendulum==2.0.4
pexpect==4.7.0
pgspecial==1.9.0
pickleshare==0.7.5
prompt-toolkit==2.0.9
psycopg2==2.7.4
ptyprocess==0.6.0
py==1.8.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.19
pycrypto==2.6.1
pyee==6.0.0
Pygments==2.4.2
pygobject==3.26.1
PyJWT==1.5.3
pynvim==0.3.2
pyOpenSSL==17.5.0
pyppeteer==0.0.25
pyquery==1.4.0
pyserial==3.4
pyTelegramBotAPI==3.6.3
python-apt==1.6.4
python-dateutil==2.8.0
python-debian==0.1.32
python-telegram-bot==12.0.0b1
pytz==2019.1
pytzdata==2019.1
pyxdg==0.25
PyYAML==3.12
regex==2019.6.8
requests==2.21.0
requests-html==0.10.0
requests-unixsocket==0.1.5
retry==0.9.2
SecretStorage==2.3.1
service-identity==16.0.0
setproctitle==1.1.10
six==1.12.0
snaptime==0.2.4
soupsieve==1.9.2
sqlparse==0.2.4
ssh-import-id==5.7
systemd-python==234
telegram==0.0.1
telegram-send==0.20
termcolor==1.1.0
timeoutcontext==1.2.0
tornado==6.0.3
tqdm==4.32.2
traitlets==4.3.2
Twisted==17.9.0
typing==3.6.6
typing-extensions==3.7.4
tzlocal==1.5.1
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
w3lib==1.20.0
wcwidth==0.1.7
websockets==7.0
yarl==1.3.0
zope.interface==4.3.2
```

**Comment by amjith** [comment]
It looks like you're using an old version of pgcli. Can you please try upgrading? 

I would recommend using `pip` to install pgcli. Take a look at the instructions on this page for linux: https://www.pgcli.com/install
