### ISSUE TITLE
pgcli + postgresql 12: colum def.adsrc not exists

### ISSUE THREAD

**Issue by alxchk** [dbcli/pgcli#1121]
## Description
Latest pgcli from pip do have issues with latest postgresql:

During startup:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in runs-mode     Refreshing completions...                                                                                                                                                
    self.__target(*self.__args, **self.__kwargs)
  File "/home/manager/.local/lib/python2.7/site-packages/pgcli/completion_refresher.py", line 65, in _bg_refresh
    refresher(completer, executor)
  File "/home/manager/.local/lib/python2.7/site-packages/pgcli/completion_refresher.py", line 109, in refresh_tables
    completer.extend_columns(executor.table_columns(), kind="tables")
  File "/home/manager/.local/lib/python2.7/site-packages/pgcli/pgcompleter.py", line 218, in extend_columns
    for schema, relname, colname, datatype, has_default, default in column_data:
  File "/home/manager/.local/lib/python2.7/site-packages/pgcli/pgexecute.py", line 591, in table_columns
    for row in self._columns(kinds=["r"]):
  File "/home/manager/.local/lib/python2.7/site-packages/pgcli/pgexecute.py", line 586, in _columns
    cur.execute(sql)
UndefinedColumn: column def.adsrc does not exist
LINE 7:                         def.adsrc as default
                                ^
```

\d failed:

```
> \d sample                                   
column c.relhasoids does not exist
LINE 2: ...                 c.relhasrules, c.relhastriggers, c.relhasoi...
                                                             ^
```

## Your environment
+ OS: Doesn't matter (Gentoo testing, Debian sid, etc)
+ Version: latest from pip 
```
pgcli --version
Version: 2.1.1
```
- Pg versions:
```
$ pip freeze | grep -i pg
pgcli==2.1.1
pgspecial==1.11.7
psycopg2==2.8.3
psycopg2-binary==2.8.4
```

**Comment by linux-mate** [comment]
I have the same problem. (Arch linux and version exactly the same except my psycopg2==2.8.4)

**Comment by abawchen** [comment]
same here

**Comment by surprisetalk** [comment]
Related to #1058

**Comment by sashaafm** [comment]
Same. Is this expected to be fixed soon? Postgres 12 has been out for some time now. Thanks!
