### ISSUE TITLE
DistributionNotFound

### ISSUE THREAD

**Issue by notaduck** [dbcli/pgcli#1124]
## Description
pgcli doesn't work after I updated my system. I might expect that it has something to do with the python upgrade from 3.7 -> 3.8

```
[~] pgcli -h 172.17.0.3 -u postgres
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pgcli==2.1.1' distribution was not found and is required by the application
```

## Your environment

- **OS** Manjaro 
- **CLI Versuib** 2.1.1-4
- https://termbin.com/n5w9

**Comment by notaduck** [comment]
I've installed the `pgcli-git` from AUR which seems to be working.
