### ISSUE TITLE
sql completion breaks shortly after connecting to DB

### ISSUE THREAD

**Issue by glw** [dbcli/pgcli#1142]
## Description
When connecting to my server SQL completion breaks shortly after connecting. Im assuming this is more do to my network or the setup of the managed DB by DigitalOcean than PGCLI. But I bring it to your attention to see if there is a better way to handle this type of situation. Or possibly a way to retry the connection to the server.

Here is the error output:
```
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in runs-mode                                             
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 673, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/share/pgcli/pgcli/pgcompleter.py", line 238, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/share/pgcli/pgcli/packages/sqlcompletion.py", line 100, in suggest_type
    full_text, identifier)
  File "/usr/share/pgcli/pgcli/packages/sqlcompletion.py", line 192, in suggest_based_on_last_token
    token_v = token.value.lower()
AttributeError: 'tuple' object has no attribute 'value'
```

## Your environment
Ubuntu Xenial
PGCLI Version: 0.20.1

Pip Freeze
```
astroid==2.3.0
beautifulsoup4==4.4.1
catfish==1.4.2
chardet==2.3.0
click==6.2
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
cycler==0.9.0
defer==1.0.6
future==0.15.2
GDAL==2.2.2
html5lib==0.999
httplib2==0.9.1
isort==4.3.21
Jinja2==2.8
language-selector==0.1
lazy-object-proxy==1.4.2
lxml==3.5.0
MarkupSafe==0.23
matplotlib==1.5.1
mccabe==0.6.1
menulibre==2.1.3
mugshot==0.3.1
numpy==1.11.0
onboard==1.2.0
OWSLib==0.14.0
pbr==5.4.1
pexpect==4.0.1
pgspecial==1.2.0
Pillow==3.1.2
plotly==1.9.5
prompt-toolkit==0.57
psutil==3.4.2
psycopg2==2.7.6.1
ptyprocess==0.5
pycups==1.9.73
pycurl==7.43.0
Pygments==2.1
pygobject==3.20.0
pylint==2.4.1
pyparsing==2.0.3
pyproj==1.9.5.1
python-apt===1.1.0.b1-ubuntu0.16.04.2-zorin1
python-dateutil==2.4.2
python-debian==0.1.27
python-systemd==231
pytz==2014.10
pyxdg==0.25
PyYAML==3.11
reportlab==3.3.0
requests==2.9.1
sessioninstaller==0.0.0
setproctitle==1.1.8
six==1.10.0
sqlparse==0.2.4
stevedore==1.30.1
typed-ast==1.2.0
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
urllib3==1.13.1
virtualenv==16.6.2
virtualenv-clone==0.5.3
virtualenvwrapper==4.8.4
wcwidth==0.1.6
wrapt==1.11.2
xkit==0.0.0
```

**Comment by amjith** [comment]
Hi. Can you try upgrading pgcli? You seem to have a very old version. The current version is 2.2.0. 

You can install it using `pip`. 

```
pip install -U pgcli
```

**Comment by glw** [comment]
hmmm its been a while since I installed or upgraded pgcli. I must have installed in using apt.  Currently it looks like version 0.20.1 is the latest for the Ubuntu repo. Is this still the recommended installation method or would pip be preferred to get more up-to-date versions?

**Comment by j-bennet** [comment]
`pip install pgcli` is preferred. Better remove the one that is apt-installed, so you don't use it accidentally.

**Comment by timxor** [comment]
What about ```pip3 install pgcli```? 

Not sure how the python v2/v3 thing for pip works and just dropping in here. 

My output for ``` pip install pgcli ``` and ```pip3 install pgcli``` on macos 10.15.2 :

```
timbo@/Users/tim.siwula/Desktop/docs:🐸:pip install pgcli
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pgcli
  Downloading https://files.pythonhosted.org/packages/19/eb/ec2d4ef9f340660695d17b70f3f4912cee675905e2cd0c5d5d0e39d1e6ba/pgcli-2.2.0.tar.gz (116kB)
     |################################| 122kB 1.6MB/s 
Collecting pgspecial>=1.11.8
  Downloading https://files.pythonhosted.org/packages/4e/0c/47957ad5b5cfb488344032326a4a013127b005929422bc5e9ee98bdf18ec/pgspecial-1.11.9.tar.gz (63kB)
     |################################| 71kB 2.0MB/s 
Requirement already satisfied: click>=4.1 in /usr/local/lib/python2.7/site-packages (from pgcli) (7.0)
Requirement already satisfied: Pygments>=2.0 in /Users/tim.siwula/Library/Python/2.7/lib/python/site-packages (from pgcli) (2.3.1)
Collecting prompt_toolkit<3.0.0,>=2.0.6
  Downloading https://files.pythonhosted.org/packages/66/6a/2c0693ec21528c10dfea279662788b28b2a01cce961160791084d975521a/prompt_toolkit-2.0.10-py2-none-any.whl (340kB)
     |################################| 348kB 2.9MB/s 
Collecting psycopg2>=2.8
  Downloading https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz (377kB)
     |################################| 378kB 3.9MB/s 
Collecting sqlparse<0.4,>=0.3.0
  Downloading https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Collecting configobj>=5.0.6
  Downloading https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Collecting humanize>=0.5.1
  Downloading https://files.pythonhosted.org/packages/8c/e0/e512e4ac6d091fc990bbe13f9e0378f34cf6eecd1c6c268c9e598dcf5bb9/humanize-0.5.1.tar.gz
Collecting cli_helpers[styles]>=1.2.0
  Downloading https://files.pythonhosted.org/packages/b1/7e/f2658b0e7cb3d4ab75d4dd5c275605ae89e56ba889dc086a0aefe6a89048/cli_helpers-1.2.1-py2-none-any.whl
Collecting setproctitle>=1.1.9
  Downloading https://files.pythonhosted.org/packages/5a/0d/dc0d2234aacba6cf1a729964383e3452c52096dc695581248b548786f2b3/setproctitle-1.1.10.tar.gz
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/site-packages (from prompt_toolkit<3.0.0,>=2.0.6->pgcli) (1.12.0)
Requirement already satisfied: wcwidth in /Users/tim.siwula/Library/Python/2.7/lib/python/site-packages (from prompt_toolkit<3.0.0,>=2.0.6->pgcli) (0.1.7)
Collecting tabulate[widechars]>=0.8.2
  Downloading https://files.pythonhosted.org/packages/c4/41/523f6a05e6dc3329a5660f6a81254c6cd87e5cfb5b7482bae3391d86ec3a/tabulate-0.8.6.tar.gz (45kB)
     |################################| 51kB 2.8MB/s 
Collecting terminaltables>=3.0.0
  Downloading https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Collecting backports.csv>=1.0.0
  Downloading https://files.pythonhosted.org/packages/8e/26/a6bd68f13e0f38fbb643d6e497fc3462be83a0b6c4d43425c78bb51a7291/backports.csv-1.0.7-py2.py3-none-any.whl
Building wheels for collected packages: pgcli, pgspecial, psycopg2, configobj, humanize, setproctitle, tabulate, terminaltables
  Building wheel for pgcli (setup.py) ... done
  Created wheel for pgcli: filename=pgcli-2.2.0-cp27-none-any.whl size=69966 sha256=49f5411b3b3b200a952f9db1cefa77ea74bb046dad324fcd81dd7a81c63610ee
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/0a/09/7f/872fc88ec93b2533998c52cea93b2d52fb72e196327850e621
  Building wheel for pgspecial (setup.py) ... done
  Created wheel for pgspecial: filename=pgspecial-1.11.9-cp27-none-any.whl size=33642 sha256=1e483a54070b4793e15df90e9b69faed0a933e51a2e5d5fb1552ef729e455b21
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/c7/c6/b9/3f26df673e76d4e5737846151fbf784070e2675e5726a5d44c
  Building wheel for psycopg2 (setup.py) ... done
  Created wheel for psycopg2: filename=psycopg2-2.8.4-cp27-cp27m-macosx_10_15_x86_64.whl size=135268 sha256=044e27559df204fd0586d269806c276121e8ac4527e6e2b3a0c6d07ecec694c0
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/7e/5b/53/30085c62689dcfce50c8f40759945a49eb856af082e9ebf751
  Building wheel for configobj (setup.py) ... done
  Created wheel for configobj: filename=configobj-5.0.6-cp27-none-any.whl size=34546 sha256=a1fd78fe9e03aa97ac5bb8e71c00cf7c416ac337d2e8312887b5876358f0903d
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/f1/e4/16/4981ca97c2d65106b49861e0b35e2660695be7219a2d351ee0
  Building wheel for humanize (setup.py) ... done
  Created wheel for humanize: filename=humanize-0.5.1-cp27-none-any.whl size=17901 sha256=74028ca98c585d86972784deda46c8363fce210d84494aa1476486fbbc70cb56
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/69/86/6c/f8b8593bc273ec4b0c653d3827f7482bb2001a2781a73b7f44
  Building wheel for setproctitle (setup.py) ... done
  Created wheel for setproctitle: filename=setproctitle-1.1.10-cp27-cp27m-macosx_10_15_x86_64.whl size=9703 sha256=bf4668af17d4ce33d5996dc665b6041d11a04a015d78285fe0e335985532231e
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/e6/b1/a6/9719530228e258eba904501fef99d5d85c80d52bd8f14438a3
  Building wheel for tabulate (setup.py) ... done
  Created wheel for tabulate: filename=tabulate-0.8.6-cp27-none-any.whl size=23273 sha256=c69d008628a47de7756679f99a28887b18459119bad3315f6147ed8dc8bf50da
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/9c/9b/f4/eb243fdb89676ec00588e8c54bb54360724c06e7fafe95278e
  Building wheel for terminaltables (setup.py) ... done
  Created wheel for terminaltables: filename=terminaltables-3.1.0-cp27-none-any.whl size=15356 sha256=c110b27da2dd96518589111874158da3e02b7128e449ab95b50c440a5ae38566
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
Successfully built pgcli pgspecial psycopg2 configobj humanize setproctitle tabulate terminaltables
ERROR: ipython 5.8.0 has requirement prompt-toolkit<2.0.0,>=1.0.4, but you'll have prompt-toolkit 2.0.10 which is incompatible.
ERROR: jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.10 which is incompatible.
Installing collected packages: sqlparse, psycopg2, pgspecial, prompt-toolkit, configobj, humanize, tabulate, terminaltables, backports.csv, cli-helpers, setproctitle, pgcli
  Found existing installation: prompt-toolkit 1.0.15
    Uninstalling prompt-toolkit-1.0.15:
      Successfully uninstalled prompt-toolkit-1.0.15
Successfully installed backports.csv-1.0.7 cli-helpers-1.2.1 configobj-5.0.6 humanize-0.5.1 pgcli-2.2.0 pgspecial-1.11.9 prompt-toolkit-2.0.10 psycopg2-2.8.4 setproctitle-1.1.10 sqlparse-0.3.0 tabulate-0.8.6 terminaltables-3.1.0
timbo@/Users/tim.siwula/Desktop/docs:🐸:pgcli            
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

timbo@/Users/tim.siwula/Desktop/docs:🐸:c

timbo@/Users/tim.siwula/Desktop/docs:🐸:pgcli
Server: PostgreSQL 12.1
Version: 2.2.0
Chat: https://gitter.im/dbcli/pgcli
Home: http://pgcli.com
tim.siwula@/tmp:tim.siwula> exit                                                                     
Goodbye!
timbo@/Users/tim.siwula/Desktop/docs:🐸:pip3 install pgcli
Collecting pgcli
  Downloading https://files.pythonhosted.org/packages/89/11/fba529b929db020fdafbfdc3d5ac33d2a30c8834e6a81cb4e104e82ee59f/pgcli-2.2.0-py3-none-any.whl (69kB)
     |████████████████████████████████| 71kB 1.8MB/s 
Collecting setproctitle>=1.1.9
  Using cached https://files.pythonhosted.org/packages/5a/0d/dc0d2234aacba6cf1a729964383e3452c52096dc695581248b548786f2b3/setproctitle-1.1.10.tar.gz
Collecting humanize>=0.5.1
  Using cached https://files.pythonhosted.org/packages/8c/e0/e512e4ac6d091fc990bbe13f9e0378f34cf6eecd1c6c268c9e598dcf5bb9/humanize-0.5.1.tar.gz
Collecting cli-helpers[styles]>=1.2.0
  Downloading https://files.pythonhosted.org/packages/51/53/d94bb9cd98cd996da6eeea82a077293cd62b825d89a36d3c27714cae5e5b/cli_helpers-1.2.1-py3-none-any.whl
Requirement already satisfied: click>=4.1 in /usr/local/lib/python3.7/site-packages (from pgcli) (7.0)
Collecting pgspecial>=1.11.8
  Using cached https://files.pythonhosted.org/packages/4e/0c/47957ad5b5cfb488344032326a4a013127b005929422bc5e9ee98bdf18ec/pgspecial-1.11.9.tar.gz
Collecting prompt-toolkit<3.0.0,>=2.0.6
  Downloading https://files.pythonhosted.org/packages/87/61/2dfea88583d5454e3a64f9308a686071d58d59a55db638268a6413e1eb6d/prompt_toolkit-2.0.10-py3-none-any.whl (340kB)
     |████████████████████████████████| 348kB 2.1MB/s 
Collecting configobj>=5.0.6
  Using cached https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Collecting Pygments>=2.0
  Downloading https://files.pythonhosted.org/packages/be/39/32da3184734730c0e4d3fa3b2b5872104668ad6dc1b5a73d8e477e5fe967/Pygments-2.5.2-py2.py3-none-any.whl (896kB)
     |████████████████████████████████| 901kB 1.8MB/s 
Collecting psycopg2>=2.8
  Using cached https://files.pythonhosted.org/packages/84/d7/6a93c99b5ba4d4d22daa3928b983cec66df4536ca50b22ce5dcac65e4e71/psycopg2-2.8.4.tar.gz
Collecting sqlparse<0.4,>=0.3.0
  Using cached https://files.pythonhosted.org/packages/ef/53/900f7d2a54557c6a37886585a91336520e5539e3ae2423ff1102daf4f3a7/sqlparse-0.3.0-py2.py3-none-any.whl
Collecting tabulate[widechars]>=0.8.2
  Using cached https://files.pythonhosted.org/packages/c4/41/523f6a05e6dc3329a5660f6a81254c6cd87e5cfb5b7482bae3391d86ec3a/tabulate-0.8.6.tar.gz
Collecting terminaltables>=3.0.0
  Using cached https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Collecting wcwidth
  Downloading https://files.pythonhosted.org/packages/58/b4/4850a0ccc6f567cc0ebe7060d20ffd4258b8210efadc259da62dc6ed9c65/wcwidth-0.1.8-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/site-packages (from prompt-toolkit<3.0.0,>=2.0.6->pgcli) (1.11.0)
Building wheels for collected packages: setproctitle, humanize, pgspecial, configobj, psycopg2, tabulate, terminaltables
  Building wheel for setproctitle (setup.py) ... done
  Created wheel for setproctitle: filename=setproctitle-1.1.10-cp37-cp37m-macosx_10_15_x86_64.whl size=10139 sha256=874419b7b8d8b5367d05ab98310d4f03c0fb6c71d6509c1374a5831414d3b8bd
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/e6/b1/a6/9719530228e258eba904501fef99d5d85c80d52bd8f14438a3
  Building wheel for humanize (setup.py) ... done
  Created wheel for humanize: filename=humanize-0.5.1-cp37-none-any.whl size=17901 sha256=fc228739f729749e418faa2a0d502a73c56234aeb02907b0760ffbdb098980b5
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/69/86/6c/f8b8593bc273ec4b0c653d3827f7482bb2001a2781a73b7f44
  Building wheel for pgspecial (setup.py) ... done
  Created wheel for pgspecial: filename=pgspecial-1.11.9-cp37-none-any.whl size=33642 sha256=ef944c1d4a03cef2c179f0002398b52a451ba5db85e83276572aed5ea79f5fe5
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/c7/c6/b9/3f26df673e76d4e5737846151fbf784070e2675e5726a5d44c
  Building wheel for configobj (setup.py) ... done
  Created wheel for configobj: filename=configobj-5.0.6-cp37-none-any.whl size=34547 sha256=78792db35176a08e1fb276f7e059071d5f22533bdb6451682a963908aef50af7
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/f1/e4/16/4981ca97c2d65106b49861e0b35e2660695be7219a2d351ee0
  Building wheel for psycopg2 (setup.py) ... done
  Created wheel for psycopg2: filename=psycopg2-2.8.4-cp37-cp37m-macosx_10_15_x86_64.whl size=135061 sha256=f46931a05a2d8623d57ace829589c6456fbf59e27322449f110e0597cf0d62fa
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/7e/5b/53/30085c62689dcfce50c8f40759945a49eb856af082e9ebf751
  Building wheel for tabulate (setup.py) ... done
  Created wheel for tabulate: filename=tabulate-0.8.6-cp37-none-any.whl size=23274 sha256=28cceaaad9f0aabbae503537151bf3e64734b9d8f54184ee47ec811287f4d889
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/9c/9b/f4/eb243fdb89676ec00588e8c54bb54360724c06e7fafe95278e
  Building wheel for terminaltables (setup.py) ... done
  Created wheel for terminaltables: filename=terminaltables-3.1.0-cp37-none-any.whl size=15355 sha256=713f21e4bbbf5dc36e69dd3d4122a9bf58e345a916ec300e3e5f52dcc28b9a43
  Stored in directory: /Users/tim.siwula/Library/Caches/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
Successfully built setproctitle humanize pgspecial configobj psycopg2 tabulate terminaltables
Installing collected packages: setproctitle, humanize, configobj, wcwidth, tabulate, terminaltables, Pygments, cli-helpers, sqlparse, psycopg2, pgspecial, prompt-toolkit, pgcli
Successfully installed Pygments-2.5.2 cli-helpers-1.2.1 configobj-5.0.6 humanize-0.5.1 pgcli-2.2.0 pgspecial-1.11.9 prompt-toolkit-2.0.10 psycopg2-2.8.4 setproctitle-1.1.10 sqlparse-0.3.0 tabulate-0.8.6 terminaltables-3.1.0 wcwidth-0.1.8
timbo@/Users/tim.siwula/Desktop/docs:🐸:c

timbo@/Users/tim.siwula/Desktop/docs:🐸:pgcli             
Server: PostgreSQL 12.1
Version: 2.2.0
Chat: https://gitter.im/dbcli/pgcli
Home: http://pgcli.com
tim.siwula@/tmp:tim.siwula>
```

**Comment by glw** [comment]
ok, thanks @j-bennet i will try installing via pip.

**Comment by glw** [comment]
This may have been why I chose apt previously to install. Below is the error I got when trying to pip install. I then tried installing ```psycopg2-binary``` but am getting the same error.
```
ERROR: Command errored out with exit status 1:
     command: /home/garret/.virtualenvs/pgcli/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mntrmanw/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mntrmanw/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-mntrmanw/psycopg2/pip-egg-info
         cwd: /tmp/pip-install-mntrmanw/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /tmp/pip-install-mntrmanw/psycopg2/pip-egg-info/psycopg2.egg-info
    writing dependency_links to /tmp/pip-install-mntrmanw/psycopg2/pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-mntrmanw/psycopg2/pip-egg-info/psycopg2.egg-info/top_level.txt
    writing /tmp/pip-install-mntrmanw/psycopg2/pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing manifest file '/tmp/pip-install-mntrmanw/psycopg2/pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This was done in a new pip virtual env. Here's a new pip list
psycopg2-binary 2.8.4  
setuptools      45.1.0 
wheel           0.34.2

**Comment by glw** [comment]
Nevermind, I didnt see the requirements further down in the README.
"pgcli requires python-dev, libpq-dev and libevent-dev packages."

Ive installed those now, and pip install runs fine. I will see if the this effects the sql completion in any way.

**Comment by glw** [comment]
So far after the update I havent had any issues like the original error I first reported.

Thanks!

**Comment by j-bennet** [comment]
@glw Thank you for reporting your findings - this may help others - and nice work resolving the issue!
