### ISSUE TITLE
RuntimeError when hitting tab for autocomplete Python 3.7.0

### ISSUE THREAD

**Issue by caje731** [dbcli/pgcli#1183]
Description
---
Halfway through typing out an INSERT statement I hit the TAB key and I get an error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/usr/share/pgcli/pgcli/pgcompleter.py", line 442, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/share/pgcli/pgcli/packages/sqlcompletion.py", line 159, in suggest_type
    return suggest_based_on_last_token(stmt.last_token, stmt)
  File "/usr/share/pgcli/pgcli/packages/sqlcompletion.py", line 388, in suggest_based_on_last_token
    Column(table_refs=stmt.get_tables('insert'), context='insert'),
  File "/usr/share/pgcli/pgcli/packages/sqlcompletion.py", line 108, in get_tables
    self.full_text if scope == 'full' else self.text_before_cursor)
  File "/usr/share/pgcli/pgcli/packages/parseutils/tables.py", line 147, in extract_tables
    return tuple(i for i in identifiers if i.name)
  File "/usr/share/pgcli/pgcli/packages/parseutils/tables.py", line 147, in <genexpr>
    return tuple(i for i in identifiers if i.name)
  File "/usr/share/pgcli/pgcli/packages/parseutils/tables.py", line 96, in extract_table_identifiers
    for item in token_stream:
RuntimeError: generator raised StopIteration
```
The exact location I hit the TAB is:

`INSERT INTO <schema.table> VALUES(`
................................................................^

Environment
---
```
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

> pgcli --version
Version: 1.9.1

> pip freeze
<blank>
```

**Comment by catherinedevlin** [comment]
As of pgcli 3.0.0, I'm not able to duplicate.  Can you update your pgcli and see if you still have the problem?

Can you test it against multiple tables and multiple databases to see if it's present consistently?

**Comment by caje731** [comment]
I cannot reproduce this on 3.0.0.
However on 1.9.1, I could reproduce it for multiple tables on the same DB.

I don't want to pursue this anymore since I can work with an upgraded pgcli.
