### ISSUE TITLE
pgcli can't connect to a remote database, but psql can.

### ISSUE THREAD

**Issue by asg0451** [dbcli/pgcli#1254]
## Description
Setting up a new environment, I can't get pgcli to talk to my postgres databases, whereas psql can. The error is:
```
could not send SSL negotiation packet: Resource temporarily unavailable
```
looking at .config/pgcli/log:
```
2021-03-01 13:43:01,770 (19095/MainThread) pgcli.main DEBUG - Database connection failed: OperationalError('could not send SSL negotiation packet: Resource temporarily unavailable\n').
2021-03-01 13:43:01,772 (19095/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/miles/.local/lib/python3.8/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/home/miles/.local/lib/python3.8/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/miles/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/miles/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/home/miles/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/home/miles/.local/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not send SSL negotiation packet: Resource temporarily unavailable\n\n'
```

Output from psql on connecting to this db:
```
psql (12.6 (Ubuntu 12.6-0ubuntu0.20.04.1), server 9.6.20)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
```

I can connect to a different AWS Redshift db through pgcli:
```
Server: PostgreSQL 8.0.2
Version: 3.1.0
Chat: https://gitter.im/dbcli/pgcli
Home: http://pgcli.com
```

## Your environment
Ubuntu 20.04
pgcli v3.1.0
pip3 freeze:
```
alabaster==0.7.8
apturl==0.5.2
awscli==1.18.69
Babel==2.6.0
bcrypt==3.1.7
blinker==1.4
botocore==1.16.19
Brlapi==0.7.0
certifi==2019.11.28
chardet==3.0.4
cli-helpers==2.1.0
Click==7.0
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
distro-info===0.23ubuntu1
docutils==0.16
duplicity==0.8.12.0
entrypoints==0.3
fasteners==0.14.1
future==0.18.2
httplib2==0.14.0
idna==2.8
imagesize==1.2.0
indicator-cpufreq==0.2.2
Jinja2==2.10.1
jmespath==0.9.4
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lockfile==0.12.2
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
MarkupSafe==1.1.0
monotonic==1.5
netifaces==0.10.4
oauthlib==3.1.0
olefile==0.46
open-fprintd==0.1
packaging==20.3
paramiko==2.6.0
pendulum==2.1.2
pexpect==4.6.0
pgcli==3.1.0
pgspecial==1.12.1
Pillow==7.0.0
pip-autoremove==0.9.1
prompt-toolkit==3.0.16
protobuf==3.6.1
psycopg2==2.8.6
pyasn1==0.4.2
pycairo==1.16.2
pycups==1.9.73
Pygments==2.3.1
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyparsing==2.4.6
pyRFC3339==1.1
python-apt==2.0.0+ubuntu0.20.4.4
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
python-validity==0.11
pytz==2019.3
pytzdata==2020.1
pyusb==1.0.2
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
roman==2.0.0
rsa==4.0
s3transfer==0.3.3
SecretStorage==2.3.1
setproctitle==1.2.2
simplejson==3.16.0
six==1.14.0
Sphinx==1.8.5
sqlparse==0.4.1
systemd-python==234
tabulate==0.8.9
terminaltables==3.1.0
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
wadllib==1.3.3
wcwidth==0.2.5
xkit==0.0.0
```

**Comment by pasenor** [comment]
If it happens on localhost, maybe changing `localhost` to `127.0.0.1` in your connection arguments. Otherwise, I'm puzzled, and it's difficult to diagnose without knowing more about your network setup.
Can you connect (using exactly the same credentials as in your pgcli invokation) with the openssl client?
```
openssl s_client -connect <HOST>:<PORT>
```

**Comment by asg0451** [comment]
thanks for getting back to me. a fresh set of eyes reveals a typo in one set of connection args. works just fine, sorry :/
