### ISSUE TITLE
Not showing SELECT query results. (Windows)

### ISSUE THREAD

**Issue by jrayga** [dbcli/pgcli#1259]
## Description

SELECT query on pgcli only shows these messages  _**Active code page: 1252 The system cannot find the file specified. on PGCLI**_

Picture here for reference
![Screenshot 2021-03-11 123803](https://user-images.githubusercontent.com/38303930/110736842-4ec97500-8267-11eb-9820-8b5ab087b3db.png)

## Your environment

- [ Windows 10 ] Please provide your OS and version information.
- [ 3.1.0 ] Please provide your CLI version.
- [  
pip freeze
alembic==1.4.2
atomicwrites==1.4.0
attrs==19.3.0
cli-helpers==2.1.0
click==7.1.1
colorama==0.4.3
configobj==5.0.6
Flask==1.1.1
Flask-Cors==3.0.8
Flask-JWT-Extended==3.24.1
flask-marshmallow==0.11.0
Flask-Migrate==2.5.3
Flask-Script==2.0.6
Flask-SQLAlchemy==2.4.1
flask-swagger-ui==3.25.0
fuzzywuzzy==0.18.0
gunicorn==20.0.4
importlib-metadata==1.6.0
itsdangerous==1.1.0
Jinja2==2.11.1
Mako==1.1.2
MarkupSafe==1.1.1
marshmallow==3.5.1
marshmallow-sqlalchemy==0.22.3
more-itertools==8.2.0
numpy==1.18.2
packaging==20.3
pendulum==2.1.2
pgcli==3.1.0
pgspecial==1.12.1
pluggy==0.13.1
prompt-toolkit==3.0.16
psycopg2==2.8.6
py==1.8.1
Pygments==2.8.1
PyJWT==1.7.1
pyparsing==2.4.7
pytest==5.4.1
python-dateutil==2.8.1
python-decouple==3.3
python-editor==1.0.4
pytz==2019.3
pytzdata==2020.1
PyYAML==5.3.1
setproctitle==1.2.2
six==1.14.0
SQLAlchemy==1.3.15
sqlparse==0.4.1
tabulate==0.8.9
terminaltables==3.1.0
wcwidth==0.1.9
Werkzeug==1.0.0
zipp==3.1.0 
] What is the output of ``pip freeze`` command.

**Comment by ERYoung11** [comment]
Does this happen for psql too or does psql work OK?

**Comment by jrayga** [comment]
> This does not happen for me with pgcli. Do you see it happens with psql too or does psql work fine?

It works on just regular PSQL cmd. I'm actually using git bash as a setting on the windows terminal. I Will try on cmd if ever

**Comment by j-bennet** [comment]
@jrayga Can you attach your log file? It would be located in your `\\AppData\\Local\\dbcli\\pgcli\\`, or whatever path is set in environment variable `XDG_CONFIG_HOME`.

**Comment by jrayga** [comment]
> @jrayga Can you attach your log file? It would be located in your `\\AppData\\Local\\dbcli\\pgcli\\`, or whatever path is set in environment variable `XDG_CONFIG_HOME`.
SLR Here's the copy

`
2021-03-11 10:51:44,350 (12956/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-11 10:51:44,350 (12956/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-11 10:51:52,853 (12956/MainThread) pgcli.pgexecute ERROR - sql: 'sel', error: SyntaxError('syntax error at or near "sel"\nLINE 1: sel\n        ^\n')
2021-03-11 10:51:52,865 (12956/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli\\pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli\\pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "sel"\nLINE 1: sel\n        ^\n\n'
2021-03-11 10:53:23,954 (17424/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-11 10:53:23,955 (17424/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-11 12:05:50,368 (11844/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-11 12:05:50,368 (11844/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-11 12:09:46,428 (2388/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-11 12:09:46,429 (2388/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-11 12:09:48,571 (2388/MainThread) pgcli.pgexecute ERROR - sql: 'selec', error: SyntaxError('syntax error at or near "selec"\nLINE 1: selec\n        ^\n')
2021-03-11 12:09:48,572 (2388/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli\\pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli\\pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "selec"\nLINE 1: selec\n        ^\n\n'
2021-03-11 12:21:03,608 (5032/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-11 12:21:03,609 (5032/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-11 12:32:56,258 (17908/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-11 12:32:56,259 (17908/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-11 12:37:17,986 (8872/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-11 12:37:17,987 (8872/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 09:20:49,186 (19128/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 09:20:49,187 (19128/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 09:22:14,171 (20164/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 09:22:14,171 (20164/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 09:22:14,261 (20164/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 582, in connect\n    raise e\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "teach_and_learnd" does not exist\n\n'
2021-03-12 09:22:16,788 (18660/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 09:22:16,788 (18660/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 09:22:16,833 (18660/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 582, in connect\n    raise e\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "teach_and_learn" does not exist\n\n'
2021-03-12 09:22:19,554 (20108/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 09:22:19,554 (20108/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 09:25:39,132 (16476/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 09:25:39,132 (16476/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 09:25:40,825 (16476/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\click\\termui.py", line 129, in prompt_func\n    return f("")\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\click\\termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\getpass.py", line 110, in win_getpass\n    raise KeyboardInterrupt\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 572, in connect\n    passwd = click.prompt(\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\click\\termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\click\\termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-03-12 09:25:44,860 (16456/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 09:25:44,860 (16456/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 09:25:45,929 (16456/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "postres"\n\n'
2021-03-12 09:25:49,438 (3840/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 09:25:49,439 (3840/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 09:25:51,365 (3840/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "postres"\n\n'
2021-03-12 09:26:03,626 (5492/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 09:26:03,627 (5492/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:06:24,894 (21392/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:06:24,895 (21392/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:07:52,729 (19184/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:07:52,730 (19184/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:08:07,681 (1784/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:08:07,682 (1784/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:08:09,701 (1784/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 582, in connect\n    raise e\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: could not send data to server: Socket is not connected (0x00002749/10057)\ncould not send SSL negotiation packet: Socket is not connected (0x00002749/10057)\n\n'
2021-03-12 11:08:17,616 (20996/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:08:17,617 (20996/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:09:13,728 (18028/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:09:13,729 (18028/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:13:15,344 (19352/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:13:15,344 (19352/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:13:39,772 (15808/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:13:39,773 (15808/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:14:18,160 (10676/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:14:18,161 (10676/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 11:16:00,180 (15652/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 11:16:00,180 (15652/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 14:49:53,307 (8948/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 14:49:53,308 (8948/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-12 14:50:07,601 (21904/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-12 14:50:07,602 (21904/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-19 11:13:05,272 (16204/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-19 11:13:05,273 (16204/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-19 11:13:07,474 (16204/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\psycopg2\\__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "xxx"\n\n'
2021-03-19 11:13:15,931 (17056/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-19 11:13:15,931 (17056/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-03-19 11:13:26,692 (17056/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2021-03-19 11:13:26,693 (17056/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "c:\\users\\xxx\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\pgcli-3.1.0-py3.8.egg\\pgcli\\pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2021-03-19 11:17:03,419 (17684/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-03-19 11:17:03,420 (17684/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").

`

**Comment by j-bennet** [comment]
The error that you have ("the system cannot find the file specified") is not showing up in `pgcli` logs. I think it might be happening inside `click` library, which is what we're using for terminal output. Probably somewhere in here:

https://github.com/pallets/click/blob/43e40c05a4b94c6aa497dc7bba62b7d69b7e35ec/src/click/_termui_impl.py#L339

I think the problem might be caused by this bug:

https://github.com/pallets/click/issues/1514

That issue was fixed in click version 7.1.2. Try installing that:

`pip install click==7.1.2`

**Comment by jrayga** [comment]
> The error that you have ("the system cannot find the file specified") is not showing up in `pgcli` logs. I think it might be happening inside `click` library, which is what we're using for terminal output. Probably somewhere in here:
> 
> https://github.com/pallets/click/blob/43e40c05a4b94c6aa497dc7bba62b7d69b7e35ec/src/click/_termui_impl.py#L339
> 
> I think the problem might be caused by this bug:
> 
> [pallets/click#1514](https://github.com/pallets/click/issues/1514)
> 
> That issue was fixed in click version 7.1.2. Try installing that:
> 
> `pip install click==7.1.2`

Yup this fixes the problem! Thank you so much.
