### ISSUE TITLE
Opening the editor crashes pgcli with IndexError in handle_editor_command

### ISSUE THREAD

**Issue by joshuaharveykeller** [dbcli/pgcli#1261]
## Description
Specifically, I run `pgcli --host=localhost --user dbuser -d database_name`, then at the prompt run `\e`.

My `$EDITOR` is set to `/usr/bin/vim/`. 

Here's the full stack trace:

```
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 11, in <module>
    load_entry_point('pgcli==2.2.0', 'console_scripts', 'console')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/pgcli/pgcli/main.py", line 1303, in cli
    pgcli.run_cli()
  File "/usr/share/pgcli/pgcli/main.py", line 726, in run_cli
    text = self.handle_editor_command(text)
  File "/usr/share/pgcli/pgcli/main.py", line 606, in handle_editor_command
    spec = text.split()[1]
IndexError: list index out of range
```

## Your environment

- Ubuntu 20.04.1 LTS (fossa-bulbasaur X38)
- pgcli Version: 2.2.0
- 
```appdirs==1.4.4
apturl==0.5.2
attrs==20.3.0
bcrypt==3.1.7
blinker==1.4
Brlapi==0.7.0
cached-property==1.5.2
certifi==2019.11.28
chardet==3.0.4
chrome-gnome-shell==0.0.0
Click==7.0
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
cryptography==2.8
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
dell-recovery==0.0.0
DellLinuxAssistant==0.0.0
distlib==0.3.1
distro==1.5.0
distro-info===0.23ubuntu1
docker==4.3.1
dockerpty==0.4.1
docopt==0.6.2
duplicity==0.8.12.0
entrypoints==0.3
fasteners==0.14.1
filelock==3.0.12
future==0.18.2
httplib2==0.14.0
humanize==1.0.0
idna==2.8
jsonschema==3.2.0
kazam==1.4.5
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lockfile==0.12.2
louis==3.12.0
macaroonbakery==1.3.1
Mako==1.1.0
MarkupSafe==1.1.0
monotonic==1.5
netifaces==0.10.4
oauthlib==3.1.0
olefile==0.46
paramiko==2.6.0
pbr==5.5.1
pexpect==4.6.0
pgspecial==1.9.0
Pillow==7.0.0
progressbar==2.5
prompt-toolkit==2.0.10
protobuf==3.6.1
psycopg2==2.8.4
pycairo==1.16.2
pycups==1.9.73
Pygments==2.3.1
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
PyQt5==5.14.1
PyQtWebEngine==5.14.0
pyRFC3339==1.1
pyrsistent==0.17.3
python-apt==2.0.0+ubuntu0.20.4.3
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
python-dotenv==0.15.0
pytz==2019.3
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
SecretStorage==2.3.1
setproctitle==1.1.10
simplejson==3.16.0
sip==4.19.21
six==1.14.0
sos==4.0
sqlparse==0.2.4
stevedore==3.2.2
systemd-python==234
tabulate==0.8.6
terminaltables==3.1.0
texttable==1.6.3
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
virtualenv==20.1.0
virtualenv-clone==0.5.4
virtualenvwrapper==4.8.4
wadllib==1.3.3
wcwidth==0.1.8
websocket-client==0.57.0
xkit==0.0.0
youtube-dl==2021.2.22```

**Comment by amjith** [comment]
I'm not able to reproduce this bug in pgcli ver 3.1.0. Would you mind upgrading pgcli? 

```
pip install -U pgcli 
```

**Comment by joshuaharveykeller** [comment]
Thanks for the suggestion, I don't know why I was running such an out-of-date version. Upgrading to 3.1.0 resolved the error.
