### ISSUE TITLE
pgcli silently fails if there's an error

### ISSUE THREAD

**Issue by farzadmf** [dbcli/pgcli#1275]
## Description
I'm trying to run an `INSERT` command that fails, but `pgcli` doesn't show any errors; example:

I create the following table:
```sql
create table my_table(col1 varchar(10) not null, col2 varchar(10))
```

Then, I try to do an invalid insertion:
```sql
insert into my_table(col2) values('should fail')
```

But `pgcli` doesn't show any errors and only shows:
```
my_db> insert into my_table(col2) values('should fail');
Time: 0.004s
```

Which gives the impression that the insertion worked and we're good to go.

Whereas trying something similar with `psql` would give these errors:
```
my_db=# insert into my_table(col2) values('should fail');
ERROR:  value too long for type character varying(10)

my_db=# insert into my_table(col2) values('shouldfail');
ERROR:  null value in column "col1" violates not-null constraint
DETAIL:  Failing row contains (null, shouldfail).
```

## Your environment

- [x] Please provide your OS and version information. __Manjaro Linux__
- [x] Please provide your CLI version. __Version: 3.1.0__
- [x] What is the output of ``pip freeze`` command. __not sure if this is helpful, but let me know and I can provide it__

**Comment by farzadmf** [comment]
No update on this? :slightly_frowning_face:

**Comment by amjith** [comment]
I get the error when I run it locally. I'm wondering if there is a pager issue. What pager are you using? Can you try to set your pager to `cat`. You can set it using `\pager cat`. 

![image](https://user-images.githubusercontent.com/49260/126076453-b1314de8-bd8e-4754-83ee-963558e04e7e.png)

**Comment by farzadmf** [comment]
Hm, I was hoping that it's a pager issue; I'm using [pspg](https://github.com/okbob/pspg/) and I have this set in my `pgcli` config:
```
pager = /usr/bin/pspg --only-for-tables --quit-if-one-screen --csv --rr=2 --ignore-case --csv-header on --pgcli-fix --style=16
```

So, I ran `pgcli` and tried again (without changing the config), and I saw no error.
I did `\pager cat`, and still no error.
I update my config to have a line saying `pager = less -SRXF` (I think this is the default) or saying `pager = cat`, but I still see no error :slightly_frowning_face: 

My `pgcli` version is also `3.1.0`

**Comment by amjith** [comment]
Can you enable debug logging in pgcli? You can do that via the config file in ~/.config/pgcli/config change the log_lever to `DEBUG`. 

Run the above commands and check the log file: ~/.config/pgcli/log. I see the following in my pgcli log file:

```
2021-07-21 08:53:08,697 (736377/MainThread) pgcli.pgbuffer DEBUG - Not in multi-line mode. Handle the buffer.
2021-07-21 08:53:08,700 (736377/MainThread) pgcli.key_bindings DEBUG - Detected enter key.
2021-07-21 08:53:08,756 (736377/MainThread) pgcli.main DEBUG - sql: "insert into my_table(col2) values('should fail');"
2021-07-21 08:53:08,771 (736377/MainThread) pgcli.pgexecute DEBUG - Trying a pgspecial command. sql: "insert into my_table(col2) values('should fail')"
2021-07-21 08:53:08,771 (736377/MainThread) pgcli.pgexecute DEBUG - Regular sql statement. sql: "insert into my_table(col2) values('should fail')"
2021-07-21 08:53:08,773 (736377/MainThread) pgcli.pgexecute ERROR - sql: "insert into my_table(col2) values('should fail')", error: StringDataRightTruncation('value too long for type character varying(10)\n')
2021-07-21 08:53:08,782 (736377/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/amjith/Dropbox/code/python/pgcli/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/amjith/Dropbox/code/python/pgcli/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/amjith/Dropbox/code/python/pgcli/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.StringDataRightTruncation: value too long for type character varying(10)\n\n'
2021-07-21 08:53:08,782 (736377/MainThread) pgcli.main DEBUG - headers: None
2021-07-21 08:53:08,782 (736377/MainThread) pgcli.main DEBUG - rows: None
2021-07-21 08:53:08,782 (736377/MainThread) pgcli.main DEBUG - status: '\x1b[31mvalue too long for type character varying(10)\n\x1b[0m'
2021-07-21 08:53:10,319 (736377/ThreadPoolExecutor-0_0) pgcli.pgcompleter DEBUG - Suggestion type: <class 'pgcli.packages.sqlcompletion.Keyword'>
2021-07-21 08:53:10,324 (736377/ThreadPoolExecutor-0_0) pgcli.pgcompleter DEBUG - Suggestion type: <class 'pgcli.packages.sqlcompletion.Special'>

```

**Comment by farzadmf** [comment]
@amjith seems like I have the exact same thing:
```
2021-07-21 12:18:18,640 (2612427/MainThread) pgcli.pgbuffer DEBUG - Not in multi-line mode. Handle the buffer.
2021-07-21 12:18:18,641 (2612427/MainThread) pgcli.key_bindings DEBUG - Detected enter key.
2021-07-21 12:18:18,659 (2612427/MainThread) pgcli.main DEBUG - sql: "insert into my_table(col2) values('should fail');"
2021-07-21 12:18:18,663 (2612427/MainThread) pgcli.pgexecute DEBUG - Trying a pgspecial command. sql: "insert into my_table(col2) values('should fail')"
2021-07-21 12:18:18,664 (2612427/MainThread) pgcli.pgexecute DEBUG - Regular sql statement. sql: "insert into my_table(col2) values('should fail')"
2021-07-21 12:18:18,665 (2612427/MainThread) pgcli.pgexecute ERROR - sql: "insert into my_table(col2) values('should fail')", error: StringDataRightTruncation('value too long for type character varying(10)\n')
2021-07-21 12:18:18,666 (2612427/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/farzad/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/farzad/.asdf/installs/python/3.9.6/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.StringDataRightTruncation: value too long for type character varying(10)\n\n'
2021-07-21 12:18:18,667 (2612427/MainThread) pgcli.main DEBUG - headers: None
2021-07-21 12:18:18,667 (2612427/MainThread) pgcli.main DEBUG - rows: None
2021-07-21 12:18:18,667 (2612427/MainThread) pgcli.main DEBUG - status: '\x1b[31mvalue too long for type character varying(10)\n\x1b[0m'
```

But how come my prompt doesn't reflect that? :slightly_frowning_face: 
```
farzad@localhost:farzad> create table my_table(col1 varchar(10) not null, col2 varchar(10));
Time: 0.014s
farzad@localhost:farzad> insert into my_table(col2) values('should fail');
Time: 0.008s
farzad@localhost:farzad>
```

**Comment by amjith** [comment]
I have a suspicion that `stderr` is being swallowed by your terminal. All error messages are printed via the stderr. 

Can you try entering gibberish in your pgcli prompt? 

![image](https://user-images.githubusercontent.com/49260/126558553-6679505b-f970-43d9-a690-a07b16dcce43.png)

What is the terminal you're using? 

One other thing I'd recommend is rename your config file (or delete it). pgcli will create the config file with defaults if it can't find a config file. That might help establish known defaults.

**Comment by farzadmf** [comment]
Very good point @amjith , deleting the config file did the trick; didn't solve the issue, but at least now I know what's at fault.

Because I'm using `pspg` as pager, I need this in the config file:
```
table_format = csv
```

However, when I set that, it seems that it's `pgcli` that's swallowing the error(s) :thinking:

**Comment by lelit** [comment]
See also #1200.

**Comment by farzadmf** [comment]
Very nice @lelit , thank you so much. Summary of what I did (in case people see this in the future):
- Removed `--pgcli-fix` and `--csv` from `pspg` options
- Set `table_format = psql` (the default)

After this, the table borders didn't look at pretty as before, so I added `--force-uniborder` to `pspg`, and now I see the errors, super nice :100: 

Closing this issue since, as far as I'm concerned, my issue is solved (thank you @lelit again)

And thank you @amjith for following up with this
