### ISSUE TITLE
How can I disable KDE wallet when starting pgcli command

### ISSUE THREAD

**Issue by mgoldchild** [dbcli/pgcli#1276]
## Description
Every time when I use pgcli, kde wallet prompt will lanch and ask me password.
How can I disable that feature on pgcli?

If i click cancel on KDE wallet then following error will be shown.

```
[mike@mike-pc ~][22:12:15][O][I][%][λ]> pgcli -h localhost -p 5432 -U postgres
Traceback (most recent call last):
File "/usr/bin/pgcli", line 33, in <module>
sys.exit(load_entry_point('pgcli==3.1.0', 'console_scripts', 'pgcli')())
File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
return self.main(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
rv = self.invoke(ctx)
File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
return __callback(*args, **kwargs)
File "/usr/lib/python3.9/site-packages/pgcli/main.py", line 1313, in cli
pgcli.connect(database, host, user, port)
File "/usr/lib/python3.9/site-packages/pgcli/main.py", line 531, in connect
passwd = keyring.get_password("pgcli", key)
File "/usr/lib/python3.9/site-packages/keyring/core.py", line 55, in get_password
return get_keyring().get_password(service_name, username)
File "/usr/lib/python3.9/site-packages/keyring/backends/chainer.py", line 51, in get_password
password = keyring.get_password(service, username)
File "/usr/lib/python3.9/site-packages/keyring/backends/kwallet.py", line 112, in get_password
raise KeyringLocked("Failed to unlock the keyring!")
keyring.errors.KeyringLocked: Failed to unlock the keyring!
```

## Your environment

- [x] Please provide your OS and version information.
- [x] Please provide your CLI version.
- [x] What is the output of ``pip freeze`` command.

```
[mike@mike-pc ~][22:14:43][O][I][%][λ]> neofetch --stdout
mike@mike-pc
------------
OS: Manjaro Linux x86_64
Host: 20KHCTO1WW ThinkPad X1 Carbon 6th
Kernel: 5.10.42-1-MANJARO
Uptime: 9 hours, 22 mins
Packages: 1720 (pacman)
Shell: zsh 5.8
Resolution: 1920x1080, 2560x1080
DE: GNOME 3.38.4
WM: Mutter
WM Theme: Matcha-dark-sea
Theme: Matcha-sea [GTK2/3]
Icons: Papirus-Dark-Maia [GTK2/3]
Terminal: tmux
CPU: Intel i5-8350U (8) @ 3.600GHz
GPU: Intel UHD Graphics 620
Memory: 6946MiB / 15761MiB
```

```
[mike@mike-pc ~][22:14:13][X][I][%][λ]> pgcli --version
Version: 3.1.0
```
```
[mike@mike-pc ~][22:14:22][O][I][%][λ]> pip show pgcli
Name: pgcli
Version: 3.1.0
Summary: CLI for Postgres Database. With auto-completion and syntax highlighting.
Home-page: http://pgcli.com
Author: Pgcli Core Team
Author-email: pgcli-dev@googlegroups.com
License: BSD
Location: /usr/lib/python3.9/site-packages
Requires: pgspecial, click, Pygments, prompt-toolkit, psycopg2, sqlparse, configobj, pendulum, cli-helpers, setproctitle
Required-by:
```

**Comment by mgoldchild** [comment]
I realized that I had set a password a long time ago, so there is no problem.

**Comment by acro5piano** [comment]
For me, removing `kwallet` disabled it completely.

```sh
sudo pacman -Rc kwallet
```

**Comment by brain90** [comment]
Works for me. Set keyring args to False

# Use keyring to automatically save and load password in a secure manner
keyring = False
