### ISSUE TITLE
Getting error `'str' object has no attribute 'parent'`

### ISSUE THREAD

**Issue by farzadmf** [dbcli/pgcli#1303]
## Description

Getting error `'str' object has no attribute 'parent'` for any command that I run

## Your environment

- [x] Please provide your OS and version information. Manjaro Linux
- [x] Please provide your CLI version. `3.2.0`
- [x] What is the output of ``pip freeze`` command.
I'm using `pgcli` inside of a virtual environment (in a directory called `/dev/data/pytools/pgcli`, and `/dev/data/pytools/pgcli/pip freeze` gives the following output:
```
cli-helpers==2.2.0
click==8.0.3
configobj==5.0.6
pendulum==2.1.2
pgcli==3.2.0
pgspecial==1.13.0
prompt-toolkit==3.0.24
psycopg2==2.9.3
Pygments==2.11.2
python-dateutil==2.8.2
pytzdata==2020.1
setproctitle==1.2.2
six==1.16.0
sqlparse==0.4.2
tabulate==0.8.9
wcwidth==0.2.5
```

I enabled `DEBUG` logging for `pgcli`, and I see the following trace back:
```
2022-01-06 09:27:37,241 (589351/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded
    on, off = self.style_string[str(ttype)]
KeyError: 'Token.Output.TableSeparator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command
    output, query = self._evaluate_command(text)
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command
    formatted = format_output(title, cur, headers, status, settings)
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output
    formatted = formatter.format_output(cur, headers, **output_kwargs)
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output
    data, headers = f(data, headers, column_types=column_types, **fkwargs)
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output
    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>
    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt
    return tabulate.Line(
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>
    *(style_field(table_separator_token, val) for val in elt)
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field
    formatter.format(((token, field),), s)
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format
    return Formatter.format(self, tokensource, outfile)
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format
    return self.format_unencoded(tokensource, outfile)
  File "/data/dev/pytools/pgcli/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded
    ttype = ttype.parent
AttributeError: 'str' object has no attribute 'parent'
```
Not sure what happened TBH. It was working before and suddenly I'm getting the error

---

UPDATE: after investigating, the issue seems to come from the [latest release 2.11.2](https://github.com/pygments/pygments/releases/tag/2.11.2) from pygments. Downgrading to `2.11.1` removes the error

**Comment by Anteru** [comment]
This must be an (unintended) side effect of https://github.com/pygments/pygments/commit/8fdd6b9879a6c34b908fa03a6ff15f764192a54e -- I'll try to investigate. You don't happen to have a minimal repro case for this? What code did you try to highlight?

**Comment by AnthonySkorski** [comment]
@Anteru spent some time on investigating [here](https://github.com/pygments/pygments/issues/2027).
I hope it will help.

**Comment by noppa** [comment]
For anyone coming to this who'd just like a temporary workaround so they can run some queries with pgcli–the expanded display still works. You can switch to it with `\x`.

**Comment by amjith** [comment]
A new version has been released with the pygments version pinned.

**Comment by Anteru** [comment]
I don't see us fixing this on the Pygments side going forward, are you planning to fix this properly? I think the cli_utils library needs to get updated.

**Comment by amjith** [comment]
@Anteru I see your [comment](https://github.com/pygments/pygments/commit/8fdd6b9879a6c34b908fa03a6ff15f764192a54e#commitcomment-63206899) on the PR. I'll take a stab at fixing it in cli_helpers.
