### ISSUE TITLE
pgcli has problem on M1 macOS Big Sur

### ISSUE THREAD

**Issue by stardiviner** [dbcli/pgcli#1311]
## Description
When I `pgcli -U <username>` connect to local PostgreSQL server on M1 macOS system. I got error:

```
❯ pgcli -U stardiviner
Traceback (most recent call last):
  File "/Users/stardiviner/opt/anaconda3/bin/pgcli", line 5, in <module>
    from pgcli.main import cli
  File "/Users/stardiviner/opt/anaconda3/lib/python3.8/site-packages/pgcli/main.py", line 6, in <module>
    from pgspecial.namedqueries import NamedQueries
  File "/Users/stardiviner/opt/anaconda3/lib/python3.8/site-packages/pgspecial/__init__.py", line 13, in <module>
    from . import iocommands
  File "/Users/stardiviner/opt/anaconda3/lib/python3.8/site-packages/pgspecial/iocommands.py", line 11, in <module>
    import psycopg2
  File "/Users/stardiviner/opt/anaconda3/lib/python3.8/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: dlopen(/Users/stardiviner/opt/anaconda3/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_PQbackendPID'
```

## Your environment

- System: M1 macOS Big Sur 12.1
- pgcli version: 3.3.1

```
pip freeze | grep pgcli
pgcli==3.3.1
```

**Comment by j-bennet** [comment]
Yes, it looks like psycopg2 has this problem with M1 macbooks. There are a few threads in psycopg repo, it looks like this solution worked for some:

https://github.com/psycopg/psycopg2/issues/1216#issuecomment-820556849

Please try this and see if it helps.

**Comment by stardiviner** [comment]
After tried your linked solution, it still does not work.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/378699/157614739-4711d4d5-8171-4b3c-b19b-1aea7d43b6c6.png">

**Comment by stardiviner** [comment]
I tried Anaconda `conda-forge` channel. It works now.
Solution: `conda install psycopg2 -c conda-forge`.
