### ISSUE TITLE
PgCli broken after updating Manjaro

### ISSUE THREAD

**Issue by warcayac** [dbcli/pgcli#1351]
## Description
Recently my Manjaro was updated and I cannot run **pgcli** anymore, I get this message:
```
Traceback (most recent call last):
  File "/home/user/.local/bin/pgcli", line 5, in <module>
    from pgcli.main import cli
  File "/home/user/.local/lib/python3.10/site-packages/pgcli/main.py", line 5, in <module>
    from pgspecial.namedqueries import NamedQueries
  File "/home/user/.local/lib/python3.10/site-packages/pgspecial/__init__.py", line 13, in <module>
    from . import iocommands
  File "/home/user/.local/lib/python3.10/site-packages/pgspecial/iocommands.py", line 10, in <module>
    import psycopg2
  File "/home/user/.local/lib/python3.10/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: libpq.so.5: cannot open shared object file: No such file or directory
```

## Your environment

- [x] Please provide your OS and version information ==> OS: Manjaro Linux x86_64, Kernel: 5.15.48-1-MANJARO
- [x] Please provide your CLI version ==> 3.4.1
- [x] What is the output of ``pip freeze`` command.
```
anytree==2.8.0
apparmor==3.0.4
appdirs==1.4.4
application-utility==1.3.2
asciinema==2.1.0
astroid==2.11.5
bcrypt==3.2.0
Beaker==1.11.0
breezy==3.2.1
btrfsutil==5.18.1
build==0.8.0
CacheControl==0.12.6
cairocffi==1.3.0
CairoSVG==2.5.2
ceph==1.0.0
ceph-volume==1.0.0
cephfs==2.0.0
cephfs-shell==0.0.1
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.10
cli-helpers==2.2.1
click==8.0.3
colorama==0.4.4
commonmark==0.9.1
configobj==5.0.6
contextlib2==0.6.0.post1
cryptography==37.0.2
cssselect2==0.5.0
cupshelpers==1.0
defusedxml==0.7.1
dill==0.3.4
distlib==0.3.4
distro==1.7.0
dnspython==2.2.1
docopt==0.6.2
docutils==0.18.1
dulwich==0.20.43
evdev==1.5.0
file-magic==0.4.0
future==0.18.2
gi-docgen==2022.1
gpg==1.17.1
html5lib==1.1
httpie==3.2.1
icoextract==0.1.3
idna==3.3
importlib-metadata==4.8.1
installer==0.5.1
isort==5.10.1
Jade-Application-Kit==3.5.7
Jinja2==3.1.2
keyutils==0.6
lazy-object-proxy==1.7.1
lensfun==0.3.3
LibAppArmor==3.0.4
libtorrent==2.0.6
lit==13.0.1.dev0
lockfile==0.12.2
louis==3.22.0
lxml==4.8.0
Mako==1.1.6
mallard-ducktype==1.0.2
manjaro-sdk==0.1
Markdown==3.3.7
MarkupSafe==2.1.1
mccabe==0.7.0
mcomix==2.0.2
meld==3.20.4
meson==0.62.2
more-itertools==8.12.0
msgpack==1.0.3
multidict==6.0.2
netsnmp-python==1.0a1
nftables==0.1
npyscreen==4.10.5
ordered-set==4.0.2
packaging==21.3
pacman-mirrors==4.23.2
paramiko==2.11.0
patiencediff==0.2.2
patool==1.12
pefile==2022.5.30
pendulum==2.1.2
pep517==0.12.0
pgcli==3.4.1
pgspecial==1.13.1
Pillow==9.1.1
platformdirs==2.5.1
ply==3.11
progress==1.6
prompt-toolkit==3.0.24
psycopg2==2.9.3
pycairo==1.21.0
pycparser==2.21
pycups==2.0.1
pycurl==7.45.1
Pygments==2.12.0
PyGObject==3.42.1
pylint==2.14.1
PyNaCl==1.5.0
pyOpenSSL==22.0.0
pyparsing==3.0.9
PyQt5==5.15.6
PyQt5-sip==12.10.1
PyQtWebEngine==5.15.5
PySide2==5.15.4
PySide6==6.3.0
pysmbc==1.0.23
PySocks==1.7.1
python-dateutil==2.8.2
pytzdata==2020.1
PyYAML==6.0
rados==2.0.0
rbd==2.0.0
reportlab==3.6.9
requests==2.27.1
requests-toolbelt==0.9.1
resolvelib==0.5.5
retrying==1.3.3
rgw==2.0.0
rich @ file:///build/python-rich/src/rich-12.4.4/dist/rich-12.4.4-py3-none-any.whl
setproctitle==1.2.2
shiboken2==5.15.4
shiboken6==6.3.0
six==1.16.0
smartypants==2.0.1
sqlparse==0.4.2
sshtunnel==0.4.0
systemd-python==234
tabulate==0.8.9
team==1.0
tinycss2==1.1.1
toml==0.10.2
tomli==2.0.1
tomlkit==0.11.0
torbrowser-launcher==0.3.5
typing-extensions==4.2.0
typogrify==2.0.7
udiskie==2.4.2
ufw==0.36.1
urllib3==1.26.9
validate==5.1.0.dev0
wcwidth==0.2.5
webencodings==0.5.1
wrapt==1.14.1
xcffib==0.11.1
zipp==3.8.0
```

**Comment by j-bennet** [comment]
Hi @warcayac ,

`pgcli` is using `psycopg2`, and `psycopg2` has several prerequisites:

https://www.psycopg.org/docs/install.html#build-prerequisites

It looks like something happened with your installation of `libpg`, which is one of the prerequisites. Try reinstalling that, as the link suggests.

**Comment by warcayac** [comment]
Dear @j-bennet , thanks for your answer. Package `libpg` does not exist.

I've solved this problem with: `pip install --upgrade psycopg2-binary`
