### ISSUE TITLE
psycopg.errors.DataCorrupted: missing chunk number 0 for toast value 16386 in pg_toast_2619 

### ISSUE THREAD

**Issue by nbari** [dbcli/pgcli#1466]
When opening pgcli and changing to a database:

```
$ pgcli
Server: PostgreSQL 15.6
Version: 4.1.0
Home: http://pgcli.com
postgres> use p0akbfib
You are now connected to database "p0akbfib" as user "postgres"
Time: 0.016s
p0akbfib> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 975, in runode  [F5] Explain: OFF      Refreshing completions...                                                        
    self._target(*self._args, **self._kwargs)
  File "/home/postgres/.local/lib/python3.11/site-packages/pgcli/completion_refresher.py", line 67, in _bg_refresh
    refresher(completer, executor)
  File "/home/postgres/.local/lib/python3.11/site-packages/pgcli/completion_refresher.py", line 127, in refresh_types
    completer.extend_datatypes(executor.datatypes())
  File "/home/postgres/.local/lib/python3.11/site-packages/pgcli/pgcompleter.py", line 314, in extend_datatypes
    for t in type_data:
  File "/home/postgres/.local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 830, in datatypes
    cur.execute(query)
  File "/home/postgres/.local/lib/python3.11/site-packages/pgcli/pgexecute.py", line 91, in execute
    super().execute(*args, **kwargs)
  File "/home/postgres/.local/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute
    raise ex.with_traceback(None)
psycopg.errors.DataCorrupted: missing chunk number 0 for toast value 16386 in pg_toast_2619
```

## Your environment

Please provide your OS and version information.: RedHat 9, but system has no internet, I am getting the sources with:

```
pip download pgcli -d package_downloads
```

And then in the VM installing with:

```
pip3.11 install --no-index --find-links="./wrk/" ./wrk/pgcli-4.1.0-py3-none-any.whl
```

Please provide your CLI version.  4.1.0

What is the output of ``pip freeze`` command.
```
pip3.11 freeze
cli_helpers==2.3.1
click==8.1.7
configobj==5.0.8
pgcli @ file:///home/postgres/wrk/pgcli-4.1.0-py3-none-any.whl
pgspecial==2.1.2
prompt_toolkit==3.0.45
psycopg==3.1.19
Pygments==2.18.0
setproctitle==1.3.3
six==1.16.0
sqlparse==0.5.0
tabulate==0.9.0
typing_extensions==4.12.1
wcwidth==0.2.13
```

**Comment by dbaty** [comment]
This is probably not related to pgli. Can you try connecting to your database with `psql` ? You are likely to have the same error. It looks like your PostgreSQL database is corrupted. If so, I'll let you search for a fix: searching the error message in a search engine ("missing chunk number for toast value") yields many results that should lead you in the right direction.

**Comment by nbari** [comment]
Hi, interestingly using `psql` works without any errors, thanks for the hints, I will search more about it.
