### ISSUE TITLE
Parsing password from the `.pg_service.conf`

### ISSUE THREAD

**Issue by ruslan-korneev** [dbcli/pgcli#1485]
## Description

When I'm trying to use pgcli with `.pg_service.conf` its crushing with this traceback, cause there is a password probably which can't be parsed by configobj library

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/pgcli", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1615, in cli
    pgcli.connect_service(service, user)
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 608, in connect_service
    service_config, file = parse_service_info(service)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1899, in parse_service_info
    raise err
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/pgcli/main.py", line 1896, in parse_service_info
    service_file_config = ConfigObj(f)
                          ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/configobj/__init__.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/opt/homebrew/Cellar/pgcli/4.1.0/libexec/lib/python3.12/site-packages/configobj/__init__.py", line 1318, in _load
    raise error
configobj.ParseError: Parse error in value at line 33.
```

generated password example: `n%{iKLJX3M0k_m/l`
I also have tried to encode this password, it didnt work out as well

## Your environment

- pgcli version: 4.1.0
- homebrew version: 4.4.0

**Comment by ruslan-korneev** [comment]
@dbaty Okay, thats weird, now it works for me, right after the incident i've started using `.pgpass` to store the passwords, and now when i've tried to reproduce the issue again - i couldnt

anyway, thanks a lot, hope nobody face this problem
