### ISSUE TITLE
Column suggestion in 2nd and subsequent columns explodes if entered text is a keyword 

### ISSUE THREAD

**Issue by drocco007** [dbcli/pgcli#228]
Many valid column names start with a prefix that is a complete keyword; this is especially true for the shorter keywords (e.g. AS, IN, IS, TO). However, if the entered text in the second or subsequent column of a SELECT clause is a complete keyword, pgcli raises an exception.

Example: enter text `SELECT 1, in`

```
postgres> SELECT 1, inException in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/drocco/.envs/brighttrac/lib/python2.7/site-packages/prompt_toolkit/__init__.py", line 472, in run
    CompleteEvent(text_inserted=True)))
  File "/home/drocco/source/foss/pgcli/pgcli/pgcompleter.py", line 201, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/home/drocco/source/foss/pgcli/pgcli/packages/sqlcompletion.py", line 86, in suggest_type
    full_text, identifier)  [F3] Multiline: OFF  [F4] Emacs-mode                                                                                                                                                                    
  File "/home/drocco/source/foss/pgcli/pgcli/packages/sqlcompletion.py", line 236, in suggest_based_on_last_token
    prev_keyword, text_before_cursor = find_prev_keyword(text_before_cursor)
  File "/home/drocco/source/foss/pgcli/pgcli/packages/parseutils.py", line 166, in find_prev_keyword
    idx = parsed.token_index(t)
  File "/home/drocco/.envs/brighttrac/lib/python2.7/site-packages/sqlparse/sql.py", line 343, in token_index
    return self.tokens.index(token)
ValueError: <Keyword 'in' at 0x7f35828f21b0> is not in list
```

Testing against f0dcb38, PG 9.3.5

**Comment by drocco007** [comment]
Hmm… just noticed that this change intersects/conflicts with @darikg's work in progress at ff9caf45

**Comment by j-bennet** [comment]
Does not crash anymore (in current 1.8.1).
