### ISSUE TITLE
pgcli --help

### ISSUE THREAD

**Issue by dongwenpeng** [dbcli/pgcli#232]
system release：centos6.5
databases version：mysql5.5
python version：python2.6

[root@localhost ~]# pgcli --help
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.16.3', 'console_scripts', 'pgcli')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 339, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2470, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2184, in load
  File "/usr/lib/python2.6/site-packages/pgcli/main.py", line 29, in <module>
    from .pgexecute import PGExecute
  File "/usr/lib/python2.6/site-packages/pgcli/pgexecute.py", line 2, in <module>
    import psycopg2
  File "/usr/lib64/python2.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: libpq.so.5: cannot open shared object file: No such file or directory

**Comment by amjith** [comment]
`pgcli` is designed to work only with Postgresql databases. It will NOT work with MySQL databases. I'm currently in the process of creating a new project that will work with MySQL.

**Comment by dongwenpeng** [comment]
Why use pgcli error --help
This it doesn't matter with Mysql

**Comment by amjith** [comment]
The last line in that error message denotes that libpq is missing on that system. libpq is a postgres library. You can install libpq by typing `$ sudo yum install postgresql-devel python-devel`.

**Comment by amjith** [comment]
Closing this issue since the reported contacted my personal email and said this is now resolved.
