### ISSUE TITLE
TypeError: sequence item 1: expected string, NoneType found

### ISSUE THREAD

**Issue by audleman** [dbcli/pgcli#291]
Typing a semicolon by itself and pressing return results in a ```TypeError```
```
$ pgcli
kevin> ;
Traceback (most recent call last):
  File "/usr/local/Cellar/pgcli/0.10.2/libexec/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.10.2', 'console_scripts', 'pgcli')()
  File "/usr/local/Cellar/pgcli/0.10.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pgcli/0.10.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pgcli/0.10.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pgcli/0.10.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pgcli/0.10.2/libexec/lib/python2.7/site-packages/pgcli/main.py", line 119, in cli
    click.secho(e.pgerror, err=True, fg='red')
  File "/usr/local/Cellar/pgcli/0.10.2/libexec/vendor/lib/python2.7/site-packages/click/termui.py", line 381, in secho
    text = style(text, **styles)
  File "/usr/local/Cellar/pgcli/0.10.2/libexec/vendor/lib/python2.7/site-packages/click/termui.py", line 354, in style
    return ''.join(bits)
TypeError: sequence item 1: expected string, NoneType found
```

**Comment by amjith** [comment]
@audleman You're using a very old version of pgcli (0.10.2). You should try upgrading. 

Can you run:

```
brew update && brew upgrade pgcli
```

**Comment by audleman** [comment]
That did the trick, thanks.
