### ISSUE TITLE
DistributionNotFound: sqlparse

### ISSUE THREAD

**Issue by cristianmtr** [dbcli/pgcli#406]
I installed pgcli with 
```
pip install -U pgcli
```

I tried running it like this:
```
pgcli <url to db>
```

I get the following traceback
```
Traceback (most recent call last):
  File "C:\Python27\Scripts\pgcli-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2867, in <module>
    working_set = WorkingSet._build_master()
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 434, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 447, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 622, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: sqlparse==0.1.16
```

I have sqlparse, since I can open a Python session and import it.

**Comment by cristianmtr** [comment]
It seems it only works with exact version. I installed that but now it's complaining about another lib
```
Traceback (most recent call last):
  File "c:\Python27\Scripts\pgcli-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2867, in <module>
    working_set = WorkingSet._build_master()
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 432, in _build_master
    ws.require(__requires__)
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 622, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: prompt-toolkit==0.46
```

Is there a way to install all dependencies?

**Comment by amjith** [comment]
That's quite puzzling. Can you tell me if you're installing it in a virtualenv? 

My suspicion is you're installing it system wide and there are other programs with conflicting dependencies. They seem to install other versions of the dependencies, which cause pgcli to fail when it launches. 

The reason for requiring specific version of prompt_toolkit is because newer versions of prompt_toolkit has some compatibility issues which we're still working through. So until then we've pinned the version to a specific value that works.

A possible remedy is to run `pip uninstall pgcli` and then run `pip install pgcli`. This will uninstall and reinstall pgcli, then try launching it. 

If that still doesn't work, can you send me the output of `pip freeze`?

**Comment by cristianmtr** [comment]
I've done that and now it's complaining about not finding a log
```
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pgcli.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\pgcli\main.py", line 564, in cli
    pgcli = PGCli(prompt_passwd, never_prompt, pgclirc_file=pgclirc)
  File "c:\python27\lib\site-packages\pgcli\main.py", line 106, in __init__
    self.initialize_logging()
  File "c:\python27\lib\site-packages\pgcli\main.py", line 166, in initialize_logging
    handler = logging.FileHandler(os.path.expanduser(log_file))
  File "c:\python27\lib\logging\__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "c:\python27\lib\logging\__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: 'C:\\Users\\<USERNAME>\\.config\\pgcli\\log'
```

**Comment by amjith** [comment]
@cristianmtr Sorry about that bug. It was a new bug introduced in the latest version, we'll get his fixed ASAP and do a quick release. 

In the meantime you can install the previous version of pgcli using `pip install pgcli==0.19.2`. That should work.

**Comment by cristianmtr** [comment]
Yes, that version seems to be working.

Thanks a lot!
