### ISSUE TITLE
Error upgrading pgcli

### ISSUE THREAD

**Issue by antonyr** [dbcli/pgcli#412]
I tried to upgrade pgcli with the command ```pip install --upgrade pgcli```

I am getting the following exception
I am also using pyenv.
```
Collecting pgcli
  Using cached pgcli-0.20.1.tar.gz
Requirement already up-to-date: pgspecial>=1.1.0 in /usr/local/var/lib/pyenv/versions/2.7/lib/python2.7/site-packages (from pgcli)
Requirement already up-to-date: click>=4.1 in /usr/local/var/lib/pyenv/versions/2.7/lib/python2.7/site-packages (from pgcli)
Requirement already up-to-date: Pygments>=2.0 in /usr/local/var/lib/pyenv/versions/2.7/lib/python2.7/site-packages (from pgcli)
Collecting prompt-toolkit==0.46 (from pgcli)
  Using cached prompt_toolkit-0.46-py2-none-any.whl
Requirement already up-to-date: psycopg2>=2.5.4 in /usr/local/var/lib/pyenv/versions/2.7/lib/python2.7/site-packages (from pgcli)
Collecting sqlparse==0.1.16 (from pgcli)
  Using cached sqlparse-0.1.16.tar.gz
Collecting configobj>=5.0.6 (from pgcli)
  Using cached configobj-5.0.6.tar.gz
Collecting setproctitle>=1.1.9 (from pgcli)
  Using cached setproctitle-1.1.9.tar.gz
Requirement already up-to-date: six>=1.9.0 in /usr/local/var/lib/pyenv/versions/2.7/lib/python2.7/site-packages (from prompt-toolkit==0.46->pgcli)
Requirement already up-to-date: wcwidth in /usr/local/var/lib/pyenv/versions/2.7/lib/python2.7/site-packages (from prompt-toolkit==0.46->pgcli)
Installing collected packages: prompt-toolkit, sqlparse, configobj, setproctitle, pgcli
  Found existing installation: prompt-toolkit 0.26
    Uninstalling prompt-toolkit-0.26:
Exception:
Traceback (most recent call last):
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/site-packages/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/shutil.py", line 292, in move
    copy2(src, real_dst)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/shutil.py", line 127, in copy2
    copyfile(src, dst)
  File "/usr/local/opt/pyenv/versions/2.7/lib/python2.7/shutil.py", line 81, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/usr/local/var/lib/pyenv/versions/2.7/bin/ptipython'
```

Please help.

**Comment by amjith** [comment]
Can you try uninstalling and try installing again? 

You can do that using: 

```
pip uninstall pgcli prompt_toolkit
pip install -U pgcli 
```

**Comment by aamirtharaj-rpx** [comment]
@amjith 
It worked now. Thank you

**Comment by amjith** [comment]
Thank you for confirming the fix. Cheers!
