### ISSUE TITLE
function does not exist. pg_catalog.pg_get_function_arguments(oid) 

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [dbcli/pgcli#414]
I have just upgraded to the latest `pgcli` with `brew`. I hadn't used it before though. 

I can connect to a database with it, and auto-complete seems to work, but I keep running into exceptions in an unpredictable manner while using it, presumably when trying to complete tables.

Below is the full trace. Anyone knows what could be failing? 

I am having this problem with both Python 2.7.10 and Python 3.5.0 (both using the latest stable version of all the install Python packages with `conda`)

Thanks!

```
$ pgcli postgresql://xxx@yyy:54321/rptdb
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
rptdb> SELECT * from 

dx.Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/completion_refresher.py", line 58, in _bg_refresh
    refresher(completer, executor)
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/completion_refresher.py", line 100, in refresh_functions
    completer.extend_functions(executor.functions())
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgcompleter.py", line 133, in extend_functions
    for f in func_data:
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 384, in functions
    cur.execute(self.functions_query)
ProgrammingError: function pg_catalog.pg_get_function_arguments(oid) does not exist
LINE 4:                 pg_catalog.pg_get_function_arguments(p.oid) ...
                        ^
HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
```

**Comment by darikg** [comment]
What version of postgresql server are you connecting to?

**Comment by amelio-vazquez-reina** [comment]
Thanks @darikg 
```
> select version();
     version
------------------------------------------------
 PostgreSQL 8.2.15 (Greenplum Database 4.3.5.2 build 1) on x86_64-unknown-linux-gnu
compiled by GCC gcc (GCC) 4.4.2 compiled on Jun 23 2015 21:03:42
(1 row)
```

Maybe this version is still not supported?

**Comment by darikg** [comment]
That's correct. Unfortunately right now we're only supporting Postgres >= 9

**Comment by amelio-vazquez-reina** [comment]
OK, thanks @darikg
