### ISSUE TITLE
Crash on startup: TypeError: encode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by brtkrbzhnv** [dbcli/pgcli#433]
It used to work fine, but then all of a sudden a few weeks ago, I was no longer able to start pgcli:

``` bash
>pgcli
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.20.1', 'console_scripts', 'pgcli')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/pgcli/main.py", line 593, in cli
    pgcli.run_cli()
  File "/Library/Python/2.7/site-packages/pgcli/main.py", line 285, in run_cli
    document = self.cli.run()
  File "/Library/Python/2.7/site-packages/prompt_toolkit/interface.py", line 271, in run
    self.renderer.request_absolute_cursor_position()
  File "/Library/Python/2.7/site-packages/prompt_toolkit/renderer.py", line 272, in request_absolute_cursor_position
    self.output.ask_for_cpr()
  File "/Library/Python/2.7/site-packages/prompt_toolkit/terminal/vt100_output.py", line 241, in ask_for_cpr
    self.flush()
  File "/Library/Python/2.7/site-packages/prompt_toolkit/terminal/vt100_output.py", line 212, in flush
    out.write(data.encode(self.stdout.encoding, 'replace'))
TypeError: encode() argument 1 must be string, not None
```

Any idea what might be wrong?

This is on Mac OS 10.11.2.

**Comment by amjith** [comment]
Can you send us the output of `pip freeze`? 

I suspect one of the dependencies got upgraded and pgcli is probably incompatible with the newer version of the library.

**Comment by brtkrbzhnv** [comment]
```
altgraph==0.10.2
bdist-mpkg==0.5.0
bonjour-py==0.3
click==6.2
configobj==5.0.6
feedparser==5.2.1
future==0.15.2
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
oauthlib==1.0.3
pgcli==0.20.1
pgsanity==0.2.8
pgspecial==1.2.0
prompt-toolkit==0.46
psycopg2==2.6.1
py2app==0.7.3
Pygments==2.0.2
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
pytz==2013.7
requests==2.4.3
requests-oauthlib==0.4.2
scipy==0.13.0b1
setproctitle==1.1.9
six==1.4.1
sqlparse==0.1.16
trakt==2.2.4
wcwidth==0.1.5
xattr==0.6.4
zope.interface==4.1.1
```

**Comment by amjith** [comment]
Nothing jumps out at the moment. I'll keep digging in. But in the meantime, can you try uninstalling and reinstalling? 

```
$ pip uninstall pgcli
$ pip install -U pgcli
```

**Comment by brtkrbzhnv** [comment]
I'm having some trouble with that:
```
>sudo pip install -U pgcli
The directory '/Users/<username>/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/<username>/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pgcli
  Downloading pgcli-0.20.1.tar.gz (46kB)
    100% |################################| 49kB 1.3MB/s 
Requirement already up-to-date: pgspecial>=1.1.0 in /Library/Python/2.7/site-packages (from pgcli)
Requirement already up-to-date: click>=4.1 in /Library/Python/2.7/site-packages (from pgcli)
Requirement already up-to-date: Pygments>=2.0 in /Library/Python/2.7/site-packages (from pgcli)
Requirement already up-to-date: prompt-toolkit==0.46 in /Library/Python/2.7/site-packages (from pgcli)
Requirement already up-to-date: psycopg2>=2.5.4 in /Library/Python/2.7/site-packages (from pgcli)
Requirement already up-to-date: sqlparse==0.1.16 in /Library/Python/2.7/site-packages (from pgcli)
Requirement already up-to-date: configobj>=5.0.6 in /Library/Python/2.7/site-packages (from pgcli)
Requirement already up-to-date: setproctitle>=1.1.9 in /Library/Python/2.7/site-packages (from pgcli)
Collecting six>=1.9.0 (from prompt-toolkit==0.46->pgcli)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit==0.46->pgcli)
  Downloading wcwidth-0.1.6-py2.py3-none-any.whl
Installing collected packages: pgcli, six, wcwidth
  Running setup.py install for pgcli
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_install.py", line 716, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/req/req_uninstall.py", line 125, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-7.1.2-py2.7.egg/pip/utils/__init__.py", line 315, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-jdyzF5-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```
Anyway, I found out that if I set the ``LANG`` environment variable to ``en_US.UTF-8`` (instead of just ``en_US``), it starts working again. Maybe pgcli could check for that during initiation?

**Comment by sanjeevkpandit** [comment]
any progress on this, I am also getting this error.

**Comment by sanjeevkpandit** [comment]
Ay progress on this? I am also getting this error.

**Comment by amjith** [comment]
@sanjeevkpandit Are you installing both mycli and pgcli on the same machine? If so, then there is a conflict in the dependency since mycli requires a newer version of prompt_toolkit.

The solution for the moment is to install pgcli from master. As follows: 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

**Comment by sanjeevkpandit** [comment]
Thanks @amjith for the quick response, it worked.
