### ISSUE TITLE
enum type unicode error in py2

### ISSUE THREAD

**Issue by GTxx** [dbcli/pgcli#437]
Hi, I have some enum type in Chinese. When I query enum value or tables using these enums, unicode encoding error raises.
```sql
my_db> select unnest(enum_range(NULL::"level"));
'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128) 
my_db> select * from book;
'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128) 
```

this is the error log:
```log
2016-01-06 09:50:27,348 (7938/MainThread) pgcli.main ERROR - sql: u'select unnest(enum_range(NULL::"level"));', error: UnicodeDecodeError('ascii', '大', 0, 1, 'ordinal not in range(128)')
2016-01-06 09:50:27,350 (7938/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):
  File "/home/my_home/.pyenv/versions/work_env/lib/python2.7/site-packages/pgcli/main.py", line 306, in run_cli
    output, query = self._evaluate_command(document.text)
  File "/home/my_home/.pyenv/versions/work_env/lib/python2.7/site-packages/pgcli/main.py", line 453, in _evaluate_command
    self.pgspecial.expanded_output, max_width)
  File "/home/my_home/.pyenv/versions/work_env/lib/python2.7/site-packages/pgcli/main.py", line 615, in format_output
    missingval='<null>')
  File "/home/my_home/.pyenv/versions/work_env/lib/python2.7/site-packages/pgcli/packages/tabulate.py", line 889, in tabulate
    ['\t'.join(map(_text_type, row)) for row in list_of_lists])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```
I think this might be similar with #426. In Python2, psycopg2 returns enum type as string object. So tabulate  fails encoding enum type value.

**Comment by amjith** [comment]
Yes I think they are related. Can you try the latest version in master? 

You can install directly from master using `pip`. 

```
pip install https://github.com/dbcli/pgcli/archive/master.zip
```

**Comment by GTxx** [comment]
Hi @amjith, latest version works for me. 
This issue is already discussed in #438. I think we can close this issue.
