### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'is_keyword'

### ISSUE THREAD

**Issue by pietdaniel** [dbcli/pgcli#445]
Just ran into this error while going about my business. Can't reproduce it but I was not doing anything out of the ordinary (typing in sql commands, using vim style keybinding to move around and alter text)

I'm running on OSX Yosemite

```python
Exception in thread Thread-145:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 509, in run
    CompleteEvent(text_inserted=True)))
  File "/usr/local/lib/python2.7/site-packages/pgcli/pgcompleter.py", line 228, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/usr/local/lib/python2.7/site-packages/pgcli/packages/sqlcompletion.py", line 85, in suggest_type
    full_text, identifier)
  File "/usr/local/lib/python2.7/site-packages/pgcli/packages/sqlcompletion.py", line 159, in suggest_based_on_last_token
    full_text, identifier)
  File "/usr/local/lib/python2.7/site-packages/pgcli/packages/sqlcompletion.py", line 256, in suggest_based_on_last_token
    elif (token_v.endswith('join') and token.is_keyword) or (token_v in
AttributeError: 'unicode' object has no attribute 'is_keyword'
```

**Comment by amjith** [comment]
Thanks you for sending the exception. That gives us some clues.

Can you tell me if there was something special about the table you were accessing? Does it have unicode characters? And would you mind telling us the schema of the table? Such as what was the different column types?

**Comment by pietdaniel** [comment]
It happened during autocompletion, I cannot disclose the schema of the table and none of the tables currently use unicode characters.

**Comment by amjith** [comment]
@pietdaniel I have a suspicion this is fixed in the newer versions of pgcli. Can you tell me what version of pgcli you're using? You can check by running `pgcli --version`.

**Comment by pietdaniel** [comment]
Version: 0.18.0

**Comment by amjith** [comment]
@pietdaniel Can you upgrade? The latest version is 0.20.1. 

You can upgrade using `pip install -U pgcli` or if you installed it via brew you can do `brew update && brew upgrade pgcli`.

**Comment by amjith** [comment]
I hope the upgrade fixed the issue for you. If you're still seeing this behavior, please reopen this issue.
