### ISSUE TITLE
year is out of range

### ISSUE THREAD

**Issue by fpietka** [dbcli/pgcli#448]
I did it by mistake, but it turns out that some old dates can't be read through pgcli.
ie. `0001-01-01 00:00:00+00:09:21 BC`

now I have to update my field from psql to get pgcli working again :grin:

**Comment by amjith** [comment]
That's odd. Unless psycopg2 has some built-in checks this shouldn't be the case. Can you send me the error message you get? 

Could you also send me the logs? You can find the logs either in ~/.pgcli.log or ~/.config/pgcli/log.

**Comment by fpietka** [comment]
Here is the error log I get:
```
2016-01-26 14:04:16,835 (9567/MainThread) pgcli.main ERROR - sql: u"select to_date('1453734279.4203', 'U');", error: ValueError('year is out of range',)
2016-01-26 14:04:16,839 (9567/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/main.py", line 306, in run_cli
    output, query = self._evaluate_command(document.text)
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/main.py", line 453, in _evaluate_command
    self.pgspecial.expanded_output, max_width)
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/main.py", line 615, in format_output
    missingval=\'<null>\')
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/packages/tabulate.py", line 884, in tabulate
    list_of_lists, headers = _normalize_tabular_data(tabular_data, headers)
  File "/usr/local/Cellar/pgcli/0.20.1/libexec/lib/python2.7/site-packages/pgcli/packages/tabulate.py", line 583, in _normalize_tabular_data
    rows = list(tabular_data)
ValueError: year is out of range
'
```

**Comment by stuartquin** [comment]
This seems like a known issue with psycopg2, it can be worked around with a custom extension like we do with json.
I'll take a look

**Comment by amjith** [comment]
This is now fixed in master. Can you try installing from master? 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

**Comment by fpietka** [comment]
Sorry for the delay. It doesn't seem to have changed.

Here is the log I got:

```
2016-02-22 10:26:48,574 (23163/MainThread) pgcli.main ERROR - sql: 'select * from test;', error: ValueError('year is out of range',)
2016-02-22 10:26:48,575 (23163/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/pgcli/main.py", line 342, in run_cli
    output, query = self._evaluate_command(document.text)
  File "/usr/local/lib/python3.4/site-packages/pgcli/main.py", line 494, in _evaluate_command
    self.pgspecial.expanded_output, max_width)
  File "/usr/local/lib/python3.4/site-packages/pgcli/main.py", line 681, in format_output
    missingval=\'<null>\')
  File "/usr/local/lib/python3.4/site-packages/pgcli/packages/tabulate.py", line 885, in tabulate
    list_of_lists, headers = _normalize_tabular_data(tabular_data, headers)
  File "/usr/local/lib/python3.4/site-packages/pgcli/packages/tabulate.py", line 584, in _normalize_tabular_data
    rows = list(tabular_data)
ValueError: year is out of range
'
```

**Comment by fernandomora** [comment]
Same error here:
`test> BEGIN;
test> CREATE TABLE test_bc(timestamptz TIMESTAMPTZ);
test> INSERT INTO test_bc(timestamptz) VALUES ('2015-01-01 00:00:00Z BC' :: timestamptz);
test> SELECT * FROM test_bc;
year is out of range
test> ROLLBACK;`

`2016-02-25 15:39:49,141 (31079/MainThread) pgcli.main ERROR - sql: u'SELECT * FROM test_bc;', error: ValueError('year is out of range',)
2016-02-25 15:39:49,142 (31079/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pgcli/main.py", line 342, in run_cli
    output, query = self._evaluate_command(document.text)
  File "/usr/local/lib/python2.7/site-packages/pgcli/main.py", line 494, in _evaluate_command
    self.pgspecial.expanded_output, max_width)
  File "/usr/local/lib/python2.7/site-packages/pgcli/main.py", line 681, in format_output
    missingval=\'<null>\')
  File "/usr/local/lib/python2.7/site-packages/pgcli/packages/tabulate.py", line 885, in tabulate
    list_of_lists, headers = _normalize_tabular_data(tabular_data, headers)
  File "/usr/local/lib/python2.7/site-packages/pgcli/packages/tabulate.py", line 584, in _normalize_tabular_data
    rows = list(tabular_data)
ValueError: year is out of range
'`

**Comment by amjith** [comment]
@fernandomora Thanks for the useful test case.

This issue is fixed in master branch but it has not been released yet. Can you try installing from master and trying again? 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

I was able to successfully query the value by running pgcli from master branch. 

@fpietka If you're still seeing the issue after installing from master, can you send me a test case?

**Comment by fernandomora** [comment]
@amjith I forgot to mention that my test case and log output is happening using master branch.

More simple test case:
```
$ pip install -U https://github.com/dbcli/pgcli/archive/master.zip
$ pgcli
SELECT ('2015-01-01 00:00:00Z BC' :: timestamptz);
year is out of range
```

**Comment by fernandomora** [comment]
I have detected this only happens with timestamps with timezones.
PR #470 should fix this.

**Comment by fpietka** [comment]
FYI, my use case is the same as @fernandomora

**Comment by amjith** [comment]
The fix proposed by @fernandomora is now merged to master. Can you try the master branch again?

**Comment by fpietka** [comment]
:+1: works like a charm!

**Comment by fpietka** [comment]
thanks
