### ISSUE TITLE
ImportError: cannot import name create_default_layout

### ISSUE THREAD

**Issue by thuandt** [dbcli/pgcli#464]
Missing module in prompt_toolkit?
```
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 7, in <module>
    from pgcli.main import cli
  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 23, in <module>
    from prompt_toolkit.shortcuts import create_default_layout, create_eventloop
ImportError: cannot import name create_default_layout
```

**Comment by gabfl** [comment]
I am getting the same error after installing pgcli with:
```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```


```
gab@xxxx:~$ pgcli
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 7, in <module>
    from pgcli.main import cli
  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 23, in <module>
    from prompt_toolkit.shortcuts import create_default_layout, create_eventloop
ImportError: cannot import name create_default_layout
```

**Comment by amjith** [comment]
What version of prompt_toolkit do you have installed?

If it not 0.57, you're going to have a bad time. 

You can check the version of prompt_toolkit by running `pip freeze | grep prompt_toolkit`

**Comment by gabfl** [comment]
Hi @amjith,

It's a confusing situation:

I need the last version of mycli due to a bug (see our exchange on https://github.com/dbcli/mycli/issues/235).

1) I installed mycli:

```
09:27 gab@xxx:~$ sudo pip install -U https://github.com/dbcli/mycli/archive/master.zip
Collecting https://github.com/dbcli/mycli/archive/master.zip
  Downloading https://github.com/dbcli/mycli/archive/master.zip (281kB)
    100% |████████████████████████████████| 286kB 1.7MB/s 
Requirement already up-to-date: click>=4.1 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Requirement already up-to-date: Pygments>=2.0 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Collecting prompt-toolkit==0.57 (from mycli==1.5.2)
  Using cached prompt_toolkit-0.57-py2-none-any.whl
Requirement already up-to-date: PyMySQL>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Collecting sqlparse>=0.1.16 (from mycli==1.5.2)
Requirement already up-to-date: configobj>=5.0.6 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Requirement already up-to-date: pycrypto>=2.6.1 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit==0.57->mycli==1.5.2)
Requirement already up-to-date: wcwidth in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit==0.57->mycli==1.5.2)
Installing collected packages: prompt-toolkit, sqlparse, mycli
  Found existing installation: prompt-toolkit 0.46
    Uninstalling prompt-toolkit-0.46:
      Successfully uninstalled prompt-toolkit-0.46
  Found existing installation: sqlparse 0.1.16
    Uninstalling sqlparse-0.1.16:
      Successfully uninstalled sqlparse-0.1.16
  Found existing installation: mycli 1.5.2
    Uninstalling mycli-1.5.2:
      Successfully uninstalled mycli-1.5.2
  Running setup.py install for mycli ... done
Successfully installed mycli-1.5.2 prompt-toolkit-0.57 sqlparse-0.1.19
```

Works as expected:
```
09:27 gab@xxx:~$ mycli
Password: 
```

pip freeze is:
```
09:28 gab@xxx:~$ pip freeze
awscli==1.9.18
botocore==1.3.18
click==6.3
colorama==0.3.3
configobj==5.0.6
docutils==0.12
helper==2.4.1
iotop==0.6
jmespath==0.9.0
Magic-file-extensions==0.2
mycli==1.5.2
newrelic-plugin-agent==1.3.0
pgcli==0.20.1
pgspecial==1.2.0
prompt-toolkit==0.57
psycopg2==2.5.4
pyasn1==0.1.9
pycrypto==2.6.1
Pygments==2.1.3
pyinotify==0.9.4
PyMySQL==0.7.2
python-dateutil==2.2
PyYAML==3.11
requests==2.9.1
rsa==3.2.3
setproctitle==1.1.9
six==1.10.0
sqlparse==0.1.19
wcwidth==0.1.6
```

2) I install pgcli with "pip install pgcli"

If I do that, pgcli works, mycli doesn't work:
```
09:26 gab@xxx:~$ sudo pip install pgcli
Requirement already satisfied (use --upgrade to upgrade): pgcli in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): configobj>=5.0.6 in /usr/local/lib/python2.7/dist-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): psycopg2>=2.5.4 in /usr/lib/python2.7/dist-packages (from pgcli)
Collecting prompt-toolkit==0.46 (from pgcli)
  Using cached prompt_toolkit-0.46-py2-none-any.whl
Collecting sqlparse==0.1.16 (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): pgspecial>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): click>=4.1 in /usr/local/lib/python2.7/dist-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): setproctitle>=1.1.9 in /usr/local/lib/python2.7/dist-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in /usr/local/lib/python2.7/dist-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from configobj>=5.0.6->pgcli)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit==0.46->pgcli)
Installing collected packages: prompt-toolkit, sqlparse
  Found existing installation: prompt-toolkit 0.57
    Uninstalling prompt-toolkit-0.57:
      Successfully uninstalled prompt-toolkit-0.57
  Found existing installation: sqlparse 0.1.19
    Uninstalling sqlparse-0.1.19:
      Successfully uninstalled sqlparse-0.1.19
Successfully installed prompt-toolkit-0.46 sqlparse-0.1.16
09:27 gab@xxx:~$ pgcli
FATAL:  database "gab" does not exist

09:27 gab@xxx:~$ mycli
Traceback (most recent call last):
  File "/usr/local/bin/mycli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 663, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 676, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'prompt-toolkit==0.57' distribution was not found and is required by mycli
```

pip freeze is:
```
09:28 gab@xxx:~$ pip freeze
awscli==1.9.18
botocore==1.3.18
click==6.3
colorama==0.3.3
configobj==5.0.6
docutils==0.12
helper==2.4.1
iotop==0.6
jmespath==0.9.0
Magic-file-extensions==0.2
mycli==1.5.2
newrelic-plugin-agent==1.3.0
pgcli==0.20.1
pgspecial==1.2.0
prompt-toolkit==0.46
psycopg2==2.5.4
pyasn1==0.1.9
pycrypto==2.6.1
Pygments==2.1.3
pyinotify==0.9.4
PyMySQL==0.7.2
python-dateutil==2.2
PyYAML==3.11
requests==2.9.1
rsa==3.2.3
setproctitle==1.1.9
six==1.10.0
sqlparse==0.1.16
wcwidth==0.1.6
```

3) I install the latest version of pgcli with "pip install -U https://github.com/dbcli/pgcli/archive/master.zip" and mycli with "pip install -U https://github.com/dbcli/pgcli/archive/master.zip"

```
09:31 gab@xxx:~$ sudo pip install -U https://github.com/dbcli/pgcli/archive/master.zip
Collecting https://github.com/dbcli/pgcli/archive/master.zip
  Downloading https://github.com/dbcli/pgcli/archive/master.zip (419kB)
    100% |████████████████████████████████| 419kB 1.4MB/s 
Requirement already up-to-date: pgspecial>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Requirement already up-to-date: click>=4.1 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Requirement already up-to-date: Pygments>=2.0 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Requirement already up-to-date: prompt-toolkit==0.57 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Requirement already up-to-date: psycopg2>=2.5.4 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Collecting sqlparse==0.1.16 (from pgcli==0.20.1)
Requirement already up-to-date: configobj>=5.0.6 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Requirement already up-to-date: humanize>=0.5.1 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Requirement already up-to-date: wcwidth>=0.1.6 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Requirement already up-to-date: setproctitle>=1.1.9 in /usr/local/lib/python2.7/dist-packages (from pgcli==0.20.1)
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit==0.57->pgcli==0.20.1)
Installing collected packages: sqlparse, pgcli
  Found existing installation: sqlparse 0.1.19
    Uninstalling sqlparse-0.1.19:
      Successfully uninstalled sqlparse-0.1.19
  Found existing installation: pgcli 0.20.1
    Uninstalling pgcli-0.20.1:
      Successfully uninstalled pgcli-0.20.1
  Running setup.py install for pgcli ... done
Successfully installed pgcli-0.20.1 sqlparse-0.1.16
09:32 gab@xxx:~$ sudo pip install -U https://github.com/dbcli/mycli/archive/master.zip
Collecting https://github.com/dbcli/mycli/archive/master.zip
  Downloading https://github.com/dbcli/mycli/archive/master.zip (281kB)
    100% |████████████████████████████████| 286kB 1.5MB/s 
Requirement already up-to-date: click>=4.1 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Requirement already up-to-date: Pygments>=2.0 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Requirement already up-to-date: prompt-toolkit==0.57 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Requirement already up-to-date: PyMySQL>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Collecting sqlparse>=0.1.16 (from mycli==1.5.2)
Requirement already up-to-date: configobj>=5.0.6 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Requirement already up-to-date: pycrypto>=2.6.1 in /usr/local/lib/python2.7/dist-packages (from mycli==1.5.2)
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit==0.57->mycli==1.5.2)
Requirement already up-to-date: wcwidth in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit==0.57->mycli==1.5.2)
Installing collected packages: sqlparse, mycli
  Found existing installation: sqlparse 0.1.16
    Uninstalling sqlparse-0.1.16:
      Successfully uninstalled sqlparse-0.1.16
  Found existing installation: mycli 1.5.2
    Uninstalling mycli-1.5.2:
      Successfully uninstalled mycli-1.5.2
  Running setup.py install for mycli ... done
Successfully installed mycli-1.5.2 sqlparse-0.1.19
```

Now pgcli does not work but mycli does:
```
09:32 gab@xxx:~$ pgcli
Traceback (most recent call last):
  File "/usr/local/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3138, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3124, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3151, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 663, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 676, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'sqlparse==0.1.16' distribution was not found and is required by pgcli
09:32 gab@xxx:~$ mycli
Password: 

09:32 gab@xxx:~$ 
```

pip freeze is:
```
awscli==1.9.18
botocore==1.3.18
click==6.3
colorama==0.3.3
configobj==5.0.6
docutils==0.12
helper==2.4.1
humanize==0.5.1
iotop==0.6
jmespath==0.9.0
Magic-file-extensions==0.2
mycli==1.5.2
newrelic-plugin-agent==1.3.0
pgcli==0.20.1
pgspecial==1.2.0
prompt-toolkit==0.57
psycopg2==2.6.1
pyasn1==0.1.9
pycrypto==2.6.1
Pygments==2.1.3
pyinotify==0.9.4
PyMySQL==0.7.2
python-dateutil==2.2
PyYAML==3.11
requests==2.9.1
rsa==3.2.3
setproctitle==1.1.9
six==1.10.0
sqlparse==0.1.19
wcwidth==0.1.6
```

Note: Regarding "prompt-toolkit". Seems install but not displayed with 
"pip freeze":
```
09:33 gab@xxx:~$ pip freeze | grep prompt_toolkit
09:33 gab@xxx:~$ sudo pip install prompt_toolkit
Requirement already satisfied (use --upgrade to upgrade): prompt-toolkit in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit)
Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit)
Requirement already satisfied (use --upgrade to upgrade): wcwidth in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit)
```


Conclusion:
I cannot get the last version of mycli (installed with "pip install -U https://github.com/dbcli/mycli/archive/master.zip") and pgcli working at the same time weather I use "pip install pgcli" or "pip install -U https://github.com/dbcli/pgcli/archive/master.zip"

Any idea?

**Comment by amjith** [comment]
Ah this is due to a mismatch in sqlparse library. I'll fix that asap. Thanks for the detailed report. I appreciate the time you took to document it.

**Comment by amjith** [comment]
@gabfl Looks like you have a newer version of sqlparse installed in your system. This version is not the right one to use with mycli or pgcli. So I'm not sure how that got installed. But I'm in the process of testing the version of sqlparse you have installed on the system. So if you need a temporary solution, my suggestion is to downgrade sqlparse using `pip install sqlparse==0.1.16`.

**Comment by gabfl** [comment]
Hi @amjith 

> This version is not the right one to use with mycli or pgcli. So I'm not sure how that got installed.

If you look above, it looks like it's installed with "pgcli":

```
sudo pip install -U https://github.com/dbcli/pgcli/archive/master.zip
Collecting https://github.com/dbcli/pgcli/archive/master.zip
[....]
  Found existing installation: sqlparse 0.1.16
    Uninstalling sqlparse-0.1.16:
      Successfully uninstalled sqlparse-0.1.16
  Found existing installation: mycli 1.5.2
    Uninstalling mycli-1.5.2:
      Successfully uninstalled mycli-1.5.2
  Running setup.py install for mycli ... done
Successfully installed mycli-1.5.2 sqlparse-0.1.19
```

**Comment by amjith** [comment]
Both pgcli and mycli now depend on the same version of `prompt_toolkit`. Please let me know if the problem still persists after an upgrade. 

```
pip install -U pgcli
```

**Comment by gabfl** [comment]
It works great, thanks a lot
