### ISSUE TITLE
Homebrew is out-of-date

### ISSUE THREAD

**Issue by doug-wade** [dbcli/pgcli#562]
I just installed `pglcli` from homebrew, and I got bit by https://github.com/dbcli/pgcli/issues/550

```
==> Summary
🍺  /usr/local/Cellar/postgresql/9.5.3: 3,142 files, 35.0M
==> Installing pgcli
==> Downloading https://homebrew.bintray.com/bottles/pgcli-1.0.0.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring pgcli-1.0.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/pgcli/1.0.0: 466 files, 4.9M
dougwade code/main ‹plat-1433*› » pgcli postgres://postgres:user@hostname:port                                                           1 ↵
Traceback (most recent call last):
  File "/usr/local/Cellar/pgcli/1.0.0/libexec/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==1.0.0', 'console_scripts', 'pgcli')()
  File "/usr/local/Cellar/pgcli/1.0.0/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pgcli/1.0.0/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pgcli/1.0.0/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pgcli/1.0.0/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pgcli/1.0.0/libexec/lib/python2.7/site-packages/pgcli/main.py", line 728, in cli
    pgcli.connect_uri(database)
  File "/usr/local/Cellar/pgcli/1.0.0/libexec/lib/python2.7/site-packages/pgcli/main.py", line 265, in connect_uri
    self.connect(*list(map(lambda p: unquote(p) if p else p, arguments)))
  File "/usr/local/Cellar/pgcli/1.0.0/libexec/lib/python2.7/site-packages/pgcli/main.py", line 265, in <lambda>
    self.connect(*list(map(lambda p: unquote(p) if p else p, arguments)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urlparse.py", line 349, in unquote
    bits = s.split('%')
AttributeError: 'int' object has no attribute 'split'
```

I expected to get a working version of pgcli.

**Comment by amjith** [comment]
I've submitted a new formula for pgcli to homebrew. https://github.com/Homebrew/homebrew-core/pull/3822

**Comment by amjith** [comment]
New formula available in brew.

**Comment by doug-wade** [comment]
Thanks @amjith!
