### ISSUE TITLE
Connection reset but no prompt to reconnect

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#725]
## Description
Connection reset by database but no prompt presented to user to reconnect. 

reported by @lazycoder-ru via gitter

## Your environment

python 2.7 
pgcli version 1.6

```
2017-06-01 16:03:43,580 (13669/MainThread) pgcli.pgexecute ERROR - sql: u'SELECT statement', error: OperationalError('server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n',)
2017-06-01 16:03:43,581 (13669/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/pgexecute.py", line 298, in run\n    yield self.execute_normal_sql(sql) + (sql, True)\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/pgexecute.py", line 333, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/pgexecute.py", line 40, in _wait_select\n    state = conn.poll()\nOperationalError: server closed the connection unexpectedly\n\tThis probably means the server terminated abnormally\n\tbefore or while processing the request.\n\n'
2017-06-01 16:03:43,581 (13669/MainThread) pgcli.main ERROR - sql: u'SELECT statement', error: KeyError(None,)
2017-06-01 16:03:43,582 (13669/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 403, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 618, in _evaluate_command\n    for title, cur, headers, status, sql, success in res:\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/pgexecute.py", line 303, in run\n    if (self._must_raise(e)\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/pgexecute.py", line 327, in _must_raise\n    psycopg2.errorcodes.lookup(e.pgcode) != \'LOCK_NOT_AVAILABLE\')\n  File "/usr/local/lib/python2.7/dist-packages/psycopg2/errorcodes.py", line 52, in lookup\n    return _cache[code]\nKeyError: None\n'
2017-06-01 16:03:50,152 (13669/MainThread) pgcli.main ERROR - sql: u'SELECT statement', error: InterfaceError('connection already closed',)
2017-06-01 16:03:50,152 (13669/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 403, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/main.py", line 618, in _evaluate_command\n    for title, cur, headers, status, sql, success in res:\n  File "/usr/local/lib/python2.7/dist-packages/pgcli/pgexecute.py", line 285, in run\n    cur = self.conn.cursor()\nInterfaceError: connection already closed\n'
2017-06-01 16:03:51,663 (13669/MainThread) pgcli.main ERROR - sql: u'SELECT statement', error: InterfaceError('connection already closed',)

```

**Comment by amjith** [comment]
Looks like catching the OperationalError is not sufficient. We need to be catching the `InterfaceError` as well. 

Needs a little bit of digging to find out why. But the simple fix is to add `InterfaceError` to the except statement here: https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L349

**Comment by donnell794** [comment]
I can take care of this addition if it has not been fulfilled

**Comment by j-bennet** [comment]
Closing via https://github.com/dbcli/pgcli/pull/743.
