### ISSUE TITLE
Cannot start program after installing with pip

### ISSUE THREAD

**Issue by torkelrogstad** [dbcli/pgcli#805]
## Description

`pgcli` crashes immediately after starting when I install it with `pip`.
``` 
$ pgcli
zsh: command not found pgcli

$ pip install pgcli
...
Successfully installed pgcli-1.8.1

$ pgcli
'NoneType' object is not subscriptable
```

After installing with `apt install pgcli` I can run the program, but then I run into the problem described in #466.

## Your environment

OS: Linux Mint 18.2 
Python version: 3.5.2
CLI version: 1.8.1
```
$ pip freeze
alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.5.1
anaconda-navigator==1.3.1
argcomplete==1.9.2
astroid==1.4.7
astropy==1.2.1
Babel==2.3.4
backports.csv==1.0.5
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.1
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.2
boto==2.42.0
Bottleneck==1.1.0
cffi==1.7.0
chest==0.2.3
cli-helpers==0.2.3
click==6.7
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.3.7
conda==4.3.29
conda-build==2.0.2
configobj==5.0.6
contextlib2==0.5.3
cryptography==1.5
cycler==0.10.0
Cython==0.24.1
cytoolz==0.8.0
dask==0.11.0
datashape==0.5.2
decorator==4.0.10
dill==0.2.5
docutils==0.12
dynd==0.7.3.dev1
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.6
Flask==0.11.1
Flask-Cors==2.1.2
gevent==1.1.2
greenlet==0.4.10
h5py==2.6.0
HeapDict==1.0.0
humanize==0.5.1
idna==2.1
imagesize==0.7.1
ipykernel==4.5.0
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.2
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
lazy-object-proxy==1.2.1
line-profiler==2.0
llvmlite==0.13.0
locket==0.2.0
lxml==3.6.4
MarkupSafe==0.23
matplotlib==1.5.3
mistune==0.7.3
mpmath==0.19
multipledispatch==0.4.8
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.1.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.1
nose==1.3.7
notebook==4.2.3
numba==0.28.1
numexpr==2.6.1
numpy==1.11.1
odo==0.5.0
openpyxl==2.3.2
pandas==0.18.1
partd==0.3.6
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pep8==1.7.0
pexpect==4.0.1
pgcli==1.8.1
pgspecial==1.8.0
pickleshare==0.7.4
Pillow==3.3.1
pkginfo==1.3.2
pluggy==0.5.2
ply==3.9
prompt-toolkit==1.0.15
psutil==4.3.1
psycopg2==2.7.3.1
ptyprocess==0.5.1
py==1.4.34
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.3.0
Pygments==2.2.0
pylint==1.5.4
pyOpenSSL==16.2.0
pyparsing==2.1.4
pysqlcipher3==1.0.2
pytest==3.2.1
python-bitcoinlib===0.8.1-PENDING
python-dateutil==2.5.3
pytz==2016.6.1
PyYAML==3.12
pyzmq==15.4.0
QtAwesome==0.3.3
qtconsole==4.2.1
QtPy==1.1.2
redis==2.10.5
requests==2.14.2
rope-py3k==0.9.4.post1
ruamel-yaml===-VERSION
scikit-image==0.12.3
scikit-learn==0.17.1
scipy==0.18.1
seaborn==0.8.1
setproctitle==1.1.10
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snakeviz==0.4.1
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.0.0
SQLAlchemy==1.0.13
sqlparse==0.2.4
statsmodels==0.6.1
sympy==1.0
tables==3.2.3.1
terminado==0.6
terminaltables==3.1.0
toolz==0.8.0
tornado==4.4.1
tox==2.9.1
traitlets==4.3.0
typing==3.6.2
unicodecsv==0.14.1
virtualenv==15.1.0
wcwidth==0.1.7
Werkzeug==0.11.11
widgetsnbextension==1.2.6
wrapt==1.10.6
xlrd==1.0.0
XlsxWriter==0.9.3
xlwt==1.1.2
```

**Comment by amjith** [comment]
That is very odd. There is a log file located at ~/.config/pgcli/log. 

Would you mind checking that file to see if there were any errors? If so, can you post the contents?

**Comment by torkelrogstad** [comment]
```
2017-10-13 23:55:24,998 (11138/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2017-10-13 23:55:25,005 (11138/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/torkel/anaconda3/lib/python3.5/site-packages/pgcli/main.py", line 380, in connect\n    **kwargs)\n  File "/home/torkel/anaconda3/lib/python3.5/site-packages/pgcli/pgexecute.py", line 173, in __init__\n    self.connect()\n  File "/home/torkel/anaconda3/lib/python3.5/site-packages/pgcli/pgexecute.py", line 225, in connect\n    self.host = self.get_socket_directory()\n  File "/home/torkel/anaconda3/lib/python3.5/site-packages/pgcli/pgexecute.py", line 509, in get_socket_directory\n    return cur.fetchone()[0]\nTypeError: \'NoneType\' object is not subscriptable\n'
```

These are the lines concerning my latest session.

**Comment by amjith** [comment]
That's really bizarre. Here's what's happening; when you launch pgcli and not provide any arguments (such as hostname), pgcli tries to guess the hostname (or the socketname). In order to find the socket it tries to find where the sockets are stored. It finds out that information by running a postgres command 

```        SELECT setting
        FROM pg_settings
        WHERE name = 'unix_socket_directories'
```

But for some reason this command is returning nothing which results in the error you're seeing. 

Remedy: You can try providing a host such as `pgcli -h 0.0.0.0` to circumvent the problem.

Root cause: I'd like to find out what caused this error to happen in the first place. Can you tell me the following information: 

1. Are you running Postgres on your local system? 
2. What version of Postgres are you running? 
3. Can you launch `psql` and run the SQL command `SELECT setting FROM pg_settings WHERE name = 'unix_socket_directories'`? What does it output?

If you'd like to have a realtime conversation, you can always jump on to gitter and have a chat. 
https://gitter.im/dbcli/pgcli

**Comment by torkelrogstad** [comment]
```
$ pgcli -h 0.0.0.0
Password:  <usual sudo password>
FATAL:  password authentication failed for user "torkel"
FATAL:  password authentication failed for user "torkel"
```

I'm running Postgres on my local system, yes. 

```
$ postgres --version
postgres (PostgreSQL) 9.5.9
```
```
$ psql
psql (9.5.9)
Type "help" for help.

torkel=> SELECT setting FROM pg_settings WHERE name = 'unix_socket_directories';
 setting 
---------
(0 rows)
```

**Comment by janpipek** [comment]
Hi, 

Fedora26 + current Anaconda + pip-installed pgsql

Also no `unix_socket_directories` in the settings, also the same NoneType error. Circumventing with `-h 0.0.0.0` allows me to use the app properly.

**Comment by j-bennet** [comment]
It is possible that `unix_socket_directories` is not present if postgresql server is only listening  on TCP. But it's surprising to me that you can get this far without providing a hostname. If I disable listening on socket, I get an error before `get_socket_directory` is even called:

```
could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```
