### ISSUE TITLE
pgcli says "connection reset" on any OperationalError

### ISSUE THREAD

**Issue by j-bennet** [dbcli/pgcli#807]
## Description

On any OperationalError, such as an invalid SQL query, pgsql says "Connection reset. Reconnect?", even though there should be no need to reconnect.

Here is an example of issuing a query to modify `pg_settings` view, for the parameter that cannot be modified in real time:

```
2017-10-21 10:29:05,537 (45148/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/Users/irina/src/pgcli/pgcli/pgexecute.py", line 319, in run\n    yield self.execute_normal_sql(sql) + (sql, True)\n  File "/Users/irina/src/pgcli/pgcli/pgexecute.py", line 355, in execute_normal_sql\n    cur.execute(split_sql)\nOperationalError: parameter "unix_socket_directories" cannot be changed without restarting the server\n\n'
2017-10-21 10:29:05,537 (45148/MainThread) pgcli.main ERROR - sql: u"update pg_settings set setting = null where name = 'unix_socket_directories'", error: OperationalError('parameter "unix_socket_directories" cannot be changed without restarting the server\n',)
```

## Your environment

pgcli 1.8.1 from master (https://github.com/dbcli/pgcli/tree/6b75bc272768879ba1043da2acf84913477bf7a0).

**Comment by dictvm** [comment]
Still happens with 1.8.2 from homebrew.

**Comment by roji** [comment]
Same here,  this is very annoying and hides the actual error.

**Comment by smilliken** [comment]
Seems to still be swallowing some recoverable errors. Two examples:

```
select count(1) from some_big_table; -- or any other long running query
Ctrl-C
```
```
copy some_table from 'non-existent-file';
```
