### ISSUE TITLE
RuntimeError: generator raised StopIteration in python 3.7.0

### ISSUE THREAD

**Issue by Incanus3** [dbcli/pgcli#902]
## Description
When trying to type in `INSERT` statement with explicit columns, e.g. "`insert into courses (`...", error is raised immediately after typing in the open bracket (probably while trying to show column names for completion). I presume python 3.7 isn't officially supported yet, I just wanted to report this so that you know about it. BTW huge thanks for the work you're doing, I love pgcli and couldn't imagine my life without it any more.

### full stack trace
```
Traceback (most recent call last):
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/pgcli/packages/parseutils/tables.py", line 38, in extract_from_part
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jakub/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/jakub/.pyenv/versions/3.7.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/pgcli/pgcompleter.py", line 442, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/pgcli/packages/sqlcompletion.py", line 159, in suggest_type
    return suggest_based_on_last_token(stmt.last_token, stmt)
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/pgcli/packages/sqlcompletion.py", line 388, in suggest_based_on_last_token
    Column(table_refs=stmt.get_tables('insert'), context='insert'),
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/pgcli/packages/sqlcompletion.py", line 108, in get_tables
    self.full_text if scope == 'full' else self.text_before_cursor)
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/pgcli/packages/parseutils/tables.py", line 147, in extract_tables
    return tuple(i for i in identifiers if i.name)
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/pgcli/packages/parseutils/tables.py", line 147, in <genexpr>
    return tuple(i for i in identifiers if i.name)
  File "/home/jakub/.pyenv/versions/3.7.0/envs/django3.7/lib/python3.7/site-packages/pgcli/packages/parseutils/tables.py", line 96, in extract_table_identifiers
    for item in token_stream:
RuntimeError: generator raised StopIteration
```

## Your environment
- [ ] Please provide your OS and version information.
`Ubuntu 18.04 LTS - GNU/Linux x86_64 4.15.0-23-generic`
- [ ] Please provide your CLI version.
`1.9.1`
- [ ] What is the output of ``pip freeze`` command.
```
backcall==0.1.0
certifi==2018.4.16
chardet==3.0.4
cli-helpers==1.0.2
click==6.7
configobj==5.0.6
coreapi==2.3.3
coreschema==0.0.4
decorator==4.3.0
Django==2.0.4
django-bootstrap3==9.1.0
django-cors-headers==2.2.0
django-extensions==2.0.7
django-filter==1.1.0
django-request-logging==0.5.5
django-rest-swagger==2.1.2
djangorestframework==3.7.7
dynamic-rest==1.8.0
Faker==0.8.13
httpie==0.9.9
humanize==0.5.1
idna==2.6
inflection==0.3.1
ipython==6.4.0
ipython-genutils==0.2.0
itypes==1.1.0
jedi==0.12.1
Jinja2==2.10
MarkupSafe==1.0
openapi-codec==1.3.2
parso==0.3.0
pexpect==4.6.0
pgcli==1.9.1
pgspecial==1.11.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
psycopg2==2.7.4
ptyprocess==0.6.0
pydash==4.5.0
Pygments==2.2.0
python-dateutil==2.7.2
pytz==2018.4
PyYAML==3.12
requests==2.18.4
rules==1.3
setproctitle==1.1.10
simplegeneric==0.8.1
simplejson==3.13.2
six==1.11.0
sqlparse==0.2.4
tabulate==0.8.2
terminaltables==3.1.0
text-unidecode==1.2
traitlets==4.3.2
uritemplate==3.0.0
urllib3==1.22
wcwidth==0.1.7
```

**Comment by vc1** [comment]
https://github.com/PyCQA/pylint/issues/2241#issuecomment-402061974

**Comment by eirnym** [comment]
MyCli had similar issue. 

With this issue this tool is completely unusable as it's easier to use `psql` to have no headache

**Comment by amjith** [comment]
Sorry guys. This is fixed in mycli. I'll see if I port over the fix to pgcli. :disappointed:
