### ISSUE TITLE
"server_version" error with Redshift

### ISSUE THREAD

**Issue by AndyFWealthfront** [dbcli/pgcli#922]
## Description
When I try to connect to a Redshift database, pgcli exits with:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/pgcli/1.10.2/libexec/bin/pgcli", line 11, in <module>
    load_entry_point('pgcli==1.10.2', 'console_scripts', 'pgcli')()
  File "/usr/local/Cellar/pgcli/1.10.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/pgcli/1.10.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/pgcli/1.10.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/pgcli/1.10.2/libexec/vendor/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/pgcli/1.10.2/libexec/lib/python2.7/site-packages/pgcli/main.py", line 1067, in cli
    pgcli.run_cli()
  File "/usr/local/Cellar/pgcli/1.10.2/libexec/lib/python2.7/site-packages/pgcli/main.py", line 629, in run_cli
    print('Server: PostgreSQL', self.pgexecute.get_server_version())
  File "/usr/local/Cellar/pgcli/1.10.2/libexec/lib/python2.7/site-packages/pgcli/pgexecute.py", line 204, in get_server_version
    cur.execute(self.version_query)
psycopg2.ProgrammingError: must be superuser to examine "server_version"
```
According to a Redshift engineer's post here, Redshift doesn't support server_version at all, even as superuser: https://stackoverflow.com/questions/51422236/what-role-permission-needed-for-the-user-to-get-the-server-version-in-amazon-red/51425825

He recommends `select version();` instead. I'm not sure how portable that is or how the output differs from server_version.

Here's what I see in my Redshift database, in case it's helpful:
```
readonly=> select current_setting('server_version');
ERROR:  must be superuser to examine "server_version"
readonly=> show server_version;
ERROR:  must be superuser to examine "server_version"
readonly=> select version();
                                                         version                                                          
--------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.2915
(1 row)
```

## Environment
Mac OS
```
~ $ pgcli --version
Version: 1.10.2
```
Installed with brew, not pip.

**Comment by j-bennet** [comment]
I'll get to this asap. In the meantime, you can work around the problem by running pgcli with `--less-chatty` to suppress the startup message.

**Comment by AndyFWealthfront** [comment]
Oh nice, thanks for the workaround!

**Comment by j-bennet** [comment]
Closed via https://github.com/dbcli/pgcli/pull/923.
