### ISSUE TITLE
No module named 'pygments.lexers._postgres_builtins'

### ISSUE THREAD

**Issue by nautilor** [dbcli/pgcli#953]
when i run pgcli i get this error

`Traceback (most recent call last):
  File "/usr/bin/pgcli", line 11, in <module>
    load_entry_point('pgcli==2.0.0', 'console_scripts', 'pgcli')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/pgcli-2.0.0-py3.6.egg/pgcli/main.py", line 41, in <module>
    from pygments.lexers.sql import PostgresLexer
  File "/usr/lib/python3.6/site-packages/pygments/lexers/sql.py", line 49, in <module>
    from pygments.lexers._postgres_builtins import KEYWORDS, DATATYPES, \
ModuleNotFoundError: No module named 'pygments.lexers._postgres_builtins'`

but i have already pygments installed

**Comment by j-bennet** [comment]
A few things to check:

* Do things work if you install pgcli in a fresh virtualenv?
* What is your `PYTHONPATH`, are you setting it in `.bashrc` somewhere?
* `which python`
* `which pip`
* `pip freeze | grep Pygments`

Does the import work from Python console?

```
--- ~ » python
Python 3.6.5 (default, Apr  5 2018, 18:08:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pygments.lexers.sql import PostgresLexer
>>>
```

**Comment by dbaty** [comment]
No news for more than 5 years and no other similar reports. I am closing this.

Original poster: feel free to reopen with details if you still have this issue.
